# db/seeds/shelf_life_seed.py
# Run once: python -m db.seeds.shelf_life_seed

SHELF_LIFE_DATA = [
    # (canonical_name, category, storage_context, min_days, avg_days, max_days, notes)

    # ── PRODUCE ──────────────────────────────────────────────────────────────────
    ("Strawberries",        "Produce", "Fridge",  3,  5,  7,  "Wash before eating, not before storing"),
    ("Blueberries",         "Produce", "Fridge",  5,  10, 14, None),
    ("Raspberries",         "Produce", "Fridge",  2,  3,  5,  None),
    ("Blackberries",        "Produce", "Fridge",  3,  5,  7,  None),
    ("Grapes",              "Produce", "Fridge",  5,  7,  14, None),
    ("Bananas",             "Produce", "Pantry",  3,  5,  7,  "Refrigerate to extend; skin blackens but fruit is fine"),
    ("Apples",              "Produce", "Fridge",  21, 30, 45, None),
    ("Apples",              "Produce", "Pantry",  5,  7,  14, None),
    ("Oranges",             "Produce", "Fridge",  14, 21, 30, None),
    ("Oranges",             "Produce", "Pantry",  5,  7,  10, None),
    ("Lemons",              "Produce", "Fridge",  14, 21, 30, None),
    ("Limes",               "Produce", "Fridge",  14, 21, 28, None),
    ("Mangoes",             "Produce", "Fridge",  5,  7,  10, "Ripen at room temp first"),
    ("Mangoes",             "Produce", "Pantry",  2,  4,  6,  "Until ripe only"),
    ("Papayas",             "Produce", "Fridge",  5,  7,  10, None),
    ("Guavas",              "Produce", "Fridge",  3,  5,  7,  None),
    ("Pomegranates",        "Produce", "Fridge",  14, 21, 30, None),
    ("Watermelon",          "Produce", "Fridge",  7,  10, 14, "Cut melon; whole can stay on counter 7-10 days"),
    ("Cantaloupe",          "Produce", "Fridge",  5,  7,  10, "Cut only"),
    ("Pineapple",           "Produce", "Fridge",  5,  7,  10, "Cut only"),
    ("Pineapple",           "Produce", "Pantry",  2,  3,  5,  "Whole, uncut"),
    ("Tomatoes",            "Produce", "Pantry",  5,  7,  10, "Refrigerating dulls flavor"),
    ("Cherry Tomatoes",     "Produce", "Fridge",  5,  7,  10, None),
    ("Onions",              "Produce", "Pantry",  14, 30, 60, "Keep dry and dark"),
    ("Garlic",              "Produce", "Pantry",  14, 30, 60, "Whole head"),
    ("Potatoes",            "Produce", "Pantry",  14, 21, 30, "Keep away from light"),
    ("Sweet Potatoes",      "Produce", "Pantry",  14, 21, 30, None),
    ("Carrots",             "Produce", "Fridge",  14, 21, 30, None),
    ("Broccoli",            "Produce", "Fridge",  3,  5,  7,  None),
    ("Cauliflower",         "Produce", "Fridge",  5,  7,  10, None),
    ("Cabbage",             "Produce", "Fridge",  14, 21, 30, None),
    ("Spinach",             "Produce", "Fridge",  3,  5,  7,  None),
    ("Lettuce",             "Produce", "Fridge",  5,  7,  10, None),
    ("Cucumber",            "Produce", "Fridge",  5,  7,  10, None),
    ("Bell Peppers",        "Produce", "Fridge",  5,  7,  14, None),
    ("Jalapeños",           "Produce", "Fridge",  5,  7,  14, None),
    ("Green Chillies",      "Produce", "Fridge",  5,  7,  14, "Common in Pakistani/Indian cooking"),
    ("Coriander",           "Produce", "Fridge",  5,  7,  10, "Also called cilantro"),
    ("Mint",                "Produce", "Fridge",  5,  7,  10, None),
    ("Green Onions",        "Produce", "Fridge",  5,  7,  10, None),
    ("Celery",              "Produce", "Fridge",  14, 21, 28, None),
    ("Mushrooms",           "Produce", "Fridge",  5,  7,  10, None),
    ("Zucchini",            "Produce", "Fridge",  5,  7,  10, None),
    ("Eggplant",            "Produce", "Fridge",  5,  7,  10, "Also called brinjal/baingan"),
    ("Corn",                "Produce", "Fridge",  1,  2,  3,  "Best eaten day of purchase"),
    ("Peas",                "Produce", "Fridge",  3,  5,  7,  "In pod; shelled peas last 3-5 days"),
    ("Green Beans",         "Produce", "Fridge",  3,  5,  7,  None),
    ("Passionfruit",        "Produce", "Fridge",  5,  7,  10,  "Best when wrinkled"),
    ("Dragonfruit",         "Produce", "Fridge",  4,  6,  8,   None),
    ("Starfruit",           "Produce", "Fridge",  5,  7,  10,  None),
    ("Persimmons",          "Produce", "Pantry",  3,  5,  7,   "Ripen at room temp"),
    ("Cherries",            "Produce", "Fridge",  5,  7,  10,  None),
    ("Apricots",            "Produce", "Fridge",  3,  5,  7,   None),
    ("Plums",               "Produce", "Fridge",  5,  7,  10,  None),
    ("Kale",                "Produce", "Fridge",  5,  7,  10,  None),
    ("Asparagus",           "Produce", "Fridge",  3,  5,  7,   None),
    ("Okra",                "Produce", "Fridge",  3,  5,  7,   "Ladyfinger; common in South Asia"),

    # ── DAIRY ────────────────────────────────────────────────────────────────────
    ("Whole Milk",          "Dairy",   "Fridge",  5,  7,  10, "After opening; check sell-by"),
    ("Skim Milk",           "Dairy",   "Fridge",  5,  7,  10, None),
    ("Full Cream Milk",     "Dairy",   "Fridge",  5,  7,  10, "Common in Pakistani/international markets"),
    ("UHT Milk",            "Dairy",   "Pantry",  60, 90, 180,"Unopened; once opened refrigerate and use in 7 days"),
    ("Half and Half",       "Dairy",   "Fridge",  5,  7,  10, None),
    ("Heavy Cream",         "Dairy",   "Fridge",  5,  7,  14, None),
    ("Butter",              "Dairy",   "Fridge",  14, 30, 45, None),
    ("Butter",              "Dairy",   "Freezer", 60, 90, 180,None),
    ("Cheddar Cheese",      "Dairy",   "Fridge",  14, 21, 30, "Opened block"),
    ("Mozzarella Cheese",   "Dairy",   "Fridge",  5,  7,  14, "Fresh; sliced or shredded"),
    ("Cream Cheese",        "Dairy",   "Fridge",  7,  14, 21, "Opened"),
    ("Cottage Cheese",      "Dairy",   "Fridge",  5,  7,  10, "Opened"),
    ("Greek Yogurt",        "Dairy",   "Fridge",  7,  14, 21, None),
    ("Plain Yogurt",        "Dairy",   "Fridge",  7,  14, 21, None),
    ("Dahi",                "Dairy",   "Fridge",  3,  5,  7,  "Pakistani-style fresh yogurt; shorter life than commercial"),
    ("Lassi",               "Dairy",   "Fridge",  2,  3,  5,  "Fresh-made; unopened commercial lasts longer"),
    ("Paneer",              "Dairy",   "Fridge",  3,  5,  7,  "Fresh Indian/Pakistani cheese; freeze for longer"),
    ("Paneer",              "Dairy",   "Freezer", 30, 60, 90, None),
    ("Eggs",                "Dairy",   "Fridge",  21, 35, 45, "From purchase date; USDA recommends refrigerating"),
    ("Sour Cream",          "Dairy",   "Fridge",  7,  14, 21, "Opened"),
    ("Whipped Cream",       "Dairy",   "Fridge",  3,  5,  7,  "Opened can or fresh"),
    ("Condensed Milk",      "Dairy",   "Pantry",  180,365,730,"Unopened; refrigerate after opening, use in 14 days"),
    ("Brie Cheese",         "Dairy",   "Fridge",  7,  14, 21,  "Soft-ripened"),
    ("Feta Cheese",         "Dairy",   "Fridge",  5,  7,  14,  "In brine"),
    ("Ricotta Cheese",      "Dairy",   "Fridge",  5,  7,  10,  None),
    ("Evaporated Milk",     "Dairy",   "Pantry",  180,365,730, "Unopened; refrigerate after opening"),
    ("Kefir",               "Dairy",   "Fridge",  7,  10, 14,  "Fermented milk drink"),
    ("Buttermilk",          "Dairy",   "Fridge",  7,  10, 14,  None),
    ("Camembert",           "Dairy",   "Fridge",  7,  14, 21,  "Soft French cheese"),

    # ── MEAT ─────────────────────────────────────────────────────────────────────
    ("Chicken Breast",      "Meat",    "Fridge",  1,  2,  3,  "Raw; cook or freeze within 2 days"),
    ("Chicken Breast",      "Meat",    "Freezer", 180,270,365,None),
    ("Chicken Thighs",      "Meat",    "Fridge",  1,  2,  3,  None),
    ("Chicken Thighs",      "Meat",    "Freezer", 180,270,365,None),
    ("Whole Chicken",       "Meat",    "Fridge",  1,  2,  3,  None),
    ("Whole Chicken",       "Meat",    "Freezer", 270,365,365,None),
    ("Minced Chicken",      "Meat",    "Fridge",  1,  2,  2,  "Also called chicken qeema"),
    ("Minced Chicken",      "Meat",    "Freezer", 90, 120,180,None),
    ("Ground Beef",         "Meat",    "Fridge",  1,  2,  2,  None),
    ("Ground Beef",         "Meat",    "Freezer", 90, 120,180,None),
    ("Beef Steak",          "Meat",    "Fridge",  2,  3,  5,  None),
    ("Beef Steak",          "Meat",    "Freezer", 180,270,365,None),
    ("Minced Beef",         "Meat",    "Fridge",  1,  2,  2,  "Also called beef qeema / keema"),
    ("Minced Beef",         "Meat",    "Freezer", 90, 120,180,None),
    ("Mutton",              "Meat",    "Fridge",  2,  3,  5,  "Common in Pakistani/Middle Eastern markets"),
    ("Mutton",              "Meat",    "Freezer", 180,270,365,None),
    ("Lamb Chops",          "Meat",    "Fridge",  2,  3,  5,  None),
    ("Lamb Chops",          "Meat",    "Freezer", 180,270,365,None),
    ("Pork Chops",          "Meat",    "Fridge",  2,  3,  5,  None),
    ("Pork Chops",          "Meat",    "Freezer", 120,180,365,None),
    ("Bacon",               "Meat",    "Fridge",  5,  7,  14, "Opened package"),
    ("Bacon",               "Meat",    "Freezer", 30, 60, 90, None),
    ("Salmon",              "Meat",    "Fridge",  1,  2,  3,  "Raw fillet"),
    ("Salmon",              "Meat",    "Freezer", 90, 180,270,None),
    ("Tuna Steak",          "Meat",    "Fridge",  1,  2,  2,  "Raw"),
    ("Tuna Steak",          "Meat",    "Freezer", 90, 180,270,None),
    ("Shrimp",              "Meat",    "Fridge",  1,  2,  3,  "Raw, peeled"),
    ("Shrimp",              "Meat",    "Freezer", 90, 180,270,None),
    ("Deli Ham",            "Meat",    "Fridge",  3,  5,  7,  "Sliced, opened package"),
    ("Deli Turkey",         "Meat",    "Fridge",  3,  5,  7,  "Sliced, opened package"),
    ("Sausages",            "Meat",    "Fridge",  3,  5,  7,  "Uncooked, opened"),
    ("Sausages",            "Meat",    "Freezer", 30, 60, 90, None),
    ("Hot Dogs",            "Meat",    "Fridge",  5,  7,  14, "Opened package"),
    ("Seekh Kebab",         "Meat",    "Fridge",  1,  2,  3,  "Raw; common in Pakistani/South Asian markets"),
    ("Seekh Kebab",         "Meat",    "Freezer", 30, 60, 90, None),
    ("Turkey Breast",       "Meat",    "Fridge",  2,  3,  5,   None),
    ("Duck Legs",           "Meat",    "Fridge",  2,  3,  5,   None),
    ("Venison",             "Meat",    "Fridge",  2,  3,  5,   "Game meat"),
    ("Goat Meat",           "Meat",    "Fridge",  2,  3,  5,   None),
    ("Crab",                "Meat",    "Fridge",  1,  2,  3,   "Raw"),
    ("Lobster",             "Meat",    "Fridge",  1,  2,  3,   None),
    ("Clams",               "Meat",    "Fridge",  1,  2,  3,   None),
    ("Oysters",             "Meat",    "Fridge",  1,  2,  2,   None),

    # ── PANTRY ───────────────────────────────────────────────────────────────────
    ("Bread",               "Pantry",  "Pantry",  5,  7,  10, "Room temp; refrigerating extends to 14 days but stales faster"),
    ("Whole Wheat Bread",   "Pantry",  "Pantry",  5,  7,  10, None),
    ("Pita Bread",          "Pantry",  "Pantry",  5,  7,  10, None),
    ("Naan",                "Bakery",  "Pantry",  2,  3,  5,  "Fresh-baked; commercial packaged lasts 5-7 days"),
    ("Roti",                "Bakery",  "Pantry",  1,  2,  3,  "Fresh flatbread; freeze for longer storage"),
    ("Roti",                "Bakery",  "Freezer", 30, 60, 90, None),
    ("Paratha",             "Bakery",  "Fridge",  2,  3,  5,  "Cooked; raw dough in fridge 3-5 days"),
    ("Paratha",             "Bakery",  "Freezer", 30, 60, 90, "Cooked parathas freeze very well"),
    ("Pasta",               "Pantry",  "Pantry",  365,730,1095,"Dry, unopened"),
    ("Rice",                "Pantry",  "Pantry",  365,730,1095,"White rice; unopened"),
    ("Basmati Rice",        "Pantry",  "Pantry",  365,730,1095,"Aromatic long-grain; common in South Asian cooking"),
    ("Oats",                "Pantry",  "Pantry",  180,365,730, "Sealed container"),
    ("Flour",               "Pantry",  "Pantry",  90, 180,365, "All-purpose; sealed"),
    ("Atta Flour",          "Pantry",  "Pantry",  60, 90, 180, "Whole wheat flour used for roti; shorter shelf life due to higher oil content"),
    ("Maida",               "Pantry",  "Pantry",  90, 180,365, "Refined flour; used in Pakistani/Indian baking"),
    ("Sugar",               "Pantry",  "Pantry",  730,1825,3650,"Indefinite if kept dry"),
    ("Salt",                "Pantry",  "Pantry",  1825,3650,3650,"Indefinite"),
    ("Olive Oil",           "Pantry",  "Pantry",  365,540,730, "Opened; store away from heat and light"),
    ("Vegetable Oil",       "Pantry",  "Pantry",  365,540,730, "Opened"),
    ("Cooking Oil",         "Pantry",  "Pantry",  180,365,540, "Generic; refined oils last longer"),
    ("Soy Sauce",           "Pantry",  "Fridge",  30, 60, 90, "After opening"),
    ("Ketchup",             "Pantry",  "Fridge",  30, 60, 90, "After opening; unopened pantry 1 year"),
    ("Mayonnaise",          "Pantry",  "Fridge",  30, 60, 90, "After opening"),
    ("Mustard",             "Pantry",  "Fridge",  60, 90, 180, "After opening"),
    ("Hot Sauce",           "Pantry",  "Fridge",  90, 180,365, "After opening"),
    ("Vinegar",             "Pantry",  "Pantry",  730,1825,3650,"Practically indefinite"),
    ("Honey",               "Pantry",  "Pantry",  730,3650,3650,"Indefinite if sealed"),
    ("Peanut Butter",       "Pantry",  "Pantry",  90, 180,270, "Natural; opened. Commercial lasts longer"),
    ("Jam",                 "Pantry",  "Fridge",  90, 180,270, "After opening"),
    ("Tomato Sauce",        "Pantry",  "Fridge",  5,  7,  10, "Opened jar"),
    ("Tomato Paste",        "Pantry",  "Fridge",  5,  7,  14, "Opened can — transfer to airtight container"),
    ("Coconut Milk",        "Pantry",  "Fridge",  4,  5,  7,  "Opened can; transfer to airtight container"),
    ("Chicken Broth",       "Pantry",  "Fridge",  3,  4,  5,  "Opened carton"),
    ("Canned Chickpeas",    "Pantry",  "Fridge",  3,  4,  5,  "Opened can; transfer to airtight container"),
    ("Canned Tomatoes",     "Pantry",  "Fridge",  3,  4,  5,  "Opened can"),
    ("Canned Tuna",         "Pantry",  "Fridge",  3,  4,  5,  "Opened can"),
    ("Lentils",             "Pantry",  "Pantry",  365,730,1095,"Dry; sealed"),
    ("Chickpeas",           "Pantry",  "Pantry",  365,730,1095,"Dry; sealed. Also called chana"),
    ("Black Beans",         "Pantry",  "Pantry",  365,730,1095,"Dry; sealed"),
    ("Masoor Dal",          "Pantry",  "Pantry",  365,730,1095,"Red lentils; common in Pakistani cooking"),
    ("Chana Dal",           "Pantry",  "Pantry",  365,730,1095,"Split chickpeas"),
    ("Moong Dal",           "Pantry",  "Pantry",  365,730,1095,"Split mung beans"),
    ("Urad Dal",            "Pantry",  "Pantry",  365,730,1095,"Black gram lentils"),
    ("Couscous",            "Pantry",  "Pantry",  365,730,1095,"Dry, sealed"),
    ("Millet",              "Pantry",  "Pantry",  365,730,1095,"Dry grain"),
    ("Barley",              "Pantry",  "Pantry",  365,730,1095,"Dry grain"),
    ("Rye Flour",           "Pantry",  "Pantry",  90, 180,365, "Sealed"),
    ("Brown Sugar",         "Pantry",  "Pantry",  365,730,1095,"Keep airtight"),
    ("Maple Syrup",         "Pantry",  "Fridge",  180,365,730, "After opening"),
    ("Tahini",              "Pantry",  "Fridge",  90, 180,270, "Sesame paste"),
    ("Molasses",            "Pantry",  "Pantry",  365,730,1095,"Sealed jar"),
    ("Coconut Oil",         "Pantry",  "Pantry",  365,540,730, "Solidifies below 24°C"),

    # ── FROZEN ───────────────────────────────────────────────────────────────────
    ("Frozen Peas",         "Frozen",  "Freezer", 180,270,365, "Keep sealed to prevent freezer burn"),
    ("Frozen Corn",         "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Spinach",      "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Mixed Veg",    "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Fries",        "Frozen",  "Freezer", 180,270,365, None),
    ("Ice Cream",           "Frozen",  "Freezer", 30, 60, 90,  "Opened; quality degrades after 2 months"),
    ("Frozen Pizza",        "Frozen",  "Freezer", 60, 90, 180, None),
    ("Frozen Waffles",      "Frozen",  "Freezer", 60, 90, 180, None),
    ("Frozen Strawberries", "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Mango",        "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Broccoli",     "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Chicken Nuggets","Frozen","Freezer", 90, 180,270, None),
    ("Frozen Fish Fillets", "Frozen",  "Freezer", 90, 180,270, None),
    ("Frozen Dumplings",    "Frozen",  "Freezer", 90, 180,270, None),

    # ── BEVERAGES ────────────────────────────────────────────────────────────────
    ("Orange Juice",        "Beverages","Fridge", 5,  7,  10, "Opened carton"),
    ("Apple Juice",         "Beverages","Fridge", 5,  7,  10, "Opened"),
    ("Sparkling Water",     "Beverages","Pantry", 365,730,730, "Unopened; opened goes flat in 1-3 days"),
    ("Soda",                "Beverages","Pantry", 180,365,540, "Unopened; opened flat in 1-3 days"),
    ("Coffee Beans",        "Beverages","Pantry", 14, 30, 60,  "Opened bag; freeze for longer"),
    ("Ground Coffee",       "Beverages","Pantry", 7,  14, 30,  "Opened bag; goes stale quickly"),
    ("Tea Bags",            "Beverages","Pantry", 180,365,730, "Sealed; loses flavor over time"),
    ("Pineapple Juice",     "Beverages","Fridge", 5,  7,  10,  "Opened carton"),
    ("Cranberry Juice",     "Beverages","Fridge", 5,  7,  10,  None),
    ("Green Tea Leaves",    "Beverages","Pantry", 180,365,730, "Sealed"),
    ("Herbal Tea",          "Beverages","Pantry", 180,365,730, None),
    ("Instant Coffee",      "Beverages","Pantry", 365,730,1095,"Sealed jar"),
    ("Energy Drink",        "Beverages","Pantry", 180,365,540, "Unopened"),

    # ── BAKERY ───────────────────────────────────────────────────────────────────
    ("Croissants",          "Bakery",  "Pantry",  1,  2,  3,  "Fresh-baked"),
    ("Bagels",              "Bakery",  "Pantry",  3,  5,  7,  None),
    ("Muffins",             "Bakery",  "Pantry",  3,  5,  7,  None),
    ("Cake",                "Bakery",  "Fridge",  3,  5,  7,  "Frosted; unfrosted lasts 2-3 days at room temp"),
    ("Scones",              "Bakery",  "Pantry",  2,  3,  5,   None),
    ("Brownies",            "Bakery",  "Pantry",  3,  5,  7,   None),
    ("Cupcakes",            "Bakery",  "Pantry",  2,  3,  5,   "Frosted"),
    ("Tarts",               "Bakery",  "Fridge",  3,  5,  7,   "Fruit-filled"),
    ("Eclairs",             "Bakery",  "Fridge",  2,  3,  5,   "Cream-filled"),
    
    # ── SNACKS ──────────────────────────────────────────────────────────────
    ("Rice Crackers",        "Snacks",  "Pantry",  90, 120,180, "Keep sealed"),
    ("Cheese Puffs",         "Snacks",  "Pantry",  60, 90, 120, "Opened bag stales quickly"),
    ("Beef Jerky",           "Snacks",  "Pantry",  180,270,365, "Unopened; refrigerate after opening"),
    ("Fruit Leather",        "Snacks",  "Pantry",  90, 120,180, None),
    ("Roasted Chickpeas",    "Snacks",  "Pantry",  60, 90, 120, "Crunchy snack"),
    ("Seaweed Snacks",       "Snacks",  "Pantry",  90, 120,180, "Keep airtight"),
    ("Crackers",             "Snacks",  "Pantry",  90, 120,180, None),

    # ── CONDIMENTS & SAUCES ────────────────────────────────────────────────
    ("Hummus",               "Condiments & Sauces","Fridge", 5, 7, 10, "Opened tub"),
    ("Tartar Sauce",         "Condiments & Sauces","Fridge", 30,60,90, None),
    ("Ranch Dressing",       "Condiments & Sauces","Fridge", 30,60,90, "Opened bottle"),
    ("Worcestershire Sauce", "Condiments & Sauces","Pantry", 365,730,1095,"Unopened"),
    ("Salsa",                "Condiments & Sauces","Fridge", 5, 7, 10, "Opened jar"),
    ("Harissa Paste",        "Condiments & Sauces","Fridge", 30,60,90, "Spicy North African paste"),
    ("Gochujang",            "Condiments & Sauces","Fridge", 60,90,180, "Korean chili paste"),

    # ── PREPARED MEALS ─────────────────────────────────────────────────────
    ("Sandwich",             "Prepared Meals","Fridge", 1, 2, 3, "Fresh-made"),
    ("Pizza Slice",          "Prepared Meals","Fridge", 2, 3, 4, "Cooked"),
    ("Sushi",                "Prepared Meals","Fridge", 1, 1, 2, "Best eaten same day"),
    ("Shawarma Wrap",        "Prepared Meals","Fridge", 1, 2, 3, "Cooked meat wrap"),
    ("Spring Rolls",         "Prepared Meals","Fridge", 2, 3, 4, "Cooked"),
    ("Pasta Salad",          "Prepared Meals","Fridge", 3, 4, 5, "With dressing"),
    ("Chicken Curry",        "Prepared Meals","Fridge", 2, 3, 4, "Cooked dish"),

    # ── BREAKFAST FOODS ────────────────────────────────────────────────────
    ("Cornflakes",           "Breakfast Foods","Pantry", 180,270,365,"Dry cereal"),
    ("Muesli",               "Breakfast Foods","Pantry", 180,270,365,"Sealed bag"),
    ("Pancake Mix",          "Breakfast Foods","Pantry", 180,270,365,"Dry powder"),
    ("Waffles",              "Breakfast Foods","Fridge", 2, 3, 5, "Fresh-made"),
    ("Bagel with Cream Cheese","Breakfast Foods","Fridge", 2, 3, 4, None),
    ("Breakfast Burrito",    "Breakfast Foods","Fridge", 2, 3, 4, "Cooked"),
    ("Scrambled Eggs",       "Breakfast Foods","Fridge", 1, 2, 3, "Cooked"),

    # ── CONFECTIONERY ─────────────────────────────────────────────────────
    ("Chocolate Bar",        "Confectionery","Pantry", 180,270,365,"Keep cool"),
    ("Hard Candy",           "Confectionery","Pantry", 365,730,1095,"Indefinite if dry"),
    ("Marshmallows",         "Confectionery","Pantry", 90, 120,180,"Opened bag"),
    ("Fudge",                "Confectionery","Pantry", 14, 21, 30, None),
    ("Truffles",             "Confectionery","Fridge", 7, 10, 14, "Handmade chocolates"),
    ("Gummy Bears",          "Confectionery","Pantry", 180,270,365,"Keep airtight"),
    ("Halva",                "Confectionery","Pantry", 90, 120,180,"Sesame sweet"),

    # ── BABY FOOD ─────────────────────────────────────────────────────────
    ("Infant Formula",       "Baby Food","Pantry", 365,540,730,"Unopened; use within 1 month after opening"),
    ("Baby Cereal",          "Baby Food","Pantry", 180,270,365,"Dry, sealed"),
    ("Pureed Carrots",       "Baby Food","Fridge", 2, 3, 4, "Opened jar"),
    ("Pureed Apples",        "Baby Food","Fridge", 2, 3, 4, None),
    ("Baby Pouches",         "Baby Food","Pantry", 180,270,365,"Unopened"),
    ("Toddler Snacks",       "Baby Food","Pantry", 90, 120,180,"Opened bag"),
    ("Rice Rusks",           "Baby Food","Pantry", 90, 120,180,"Dry snack for infants"),
]


def seed_shelf_life(db_session):
    """
    Insert all shelf_life_reference rows.
    Safe to run multiple times — skips rows that already exist.
    Call from your Alembic migration or a one-time setup script.
    """
    from app.models import ShelfLifeReference

    inserted = 0
    for row in SHELF_LIFE_DATA:
        canonical_name, category, storage_context, min_d, avg_d, max_d, notes = row
        exists = db_session.query(ShelfLifeReference).filter_by(
            canonical_name=canonical_name,
            storage_context=storage_context,
        ).first()
        if not exists:
            db_session.add(ShelfLifeReference(
                canonical_name=canonical_name,
                category=category,
                storage_context=storage_context,
                shelf_life_days_min=min_d,
                shelf_life_days_avg=avg_d,
                shelf_life_days_max=max_d,
                notes=notes,
            ))
            inserted += 1

    db_session.commit()
    print(f"Seeded {inserted} shelf_life_reference rows ({len(SHELF_LIFE_DATA) - inserted} already existed)")