# db/seeds/shelf_life_seed.py
# Run once: python -m db.seeds.shelf_life_seed

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from app.models import ShelfLifeReference
from app.db import SessionLocal

SHELF_LIFE_DATA = [
    # (canonical_name, category, storage_context, min_days, avg_days, max_days, notes)

    # ── PRODUCE ──────────────────────────────────────────────────────────────────
    ("Strawberries",        "Produce", "Fridge",  3,  5,  7,  "Wash before eating, not before storing"),
    ("Blueberries",         "Produce", "Fridge",  5,  10, 14, None),
    ("Raspberries",         "Produce", "Fridge",  2,  3,  5,  None),
    ("Blackberries",        "Produce", "Fridge",  3,  5,  7,  None),
    ("Grapes",              "Produce", "Fridge",  5,  7,  14, None),
    ("Bananas",             "Produce", "Pantry",  3,  5,  7,  "Refrigerate to extend; skin blackens but fruit is fine"),
    ("Apples",              "Produce", "Fridge",  21, 30, 45, None),
    ("Apples",              "Produce", "Pantry",  5,  7,  14, None),
    ("Oranges",             "Produce", "Fridge",  14, 21, 30, None),
    ("Oranges",             "Produce", "Pantry",  5,  7,  10, None),
    ("Lemons",              "Produce", "Fridge",  14, 21, 30, None),
    ("Limes",               "Produce", "Fridge",  14, 21, 28, None),
    ("Mangoes",             "Produce", "Fridge",  5,  7,  10, "Ripen at room temp first"),
    ("Mangoes",             "Produce", "Pantry",  2,  4,  6,  "Until ripe only"),
    ("Papayas",             "Produce", "Fridge",  5,  7,  10, None),
    ("Guavas",              "Produce", "Fridge",  3,  5,  7,  None),
    ("Pomegranates",        "Produce", "Fridge",  14, 21, 30, None),
    ("Watermelon",          "Produce", "Pantry", 7, 10, 14, "Whole uncut; cut melon refrigerate and use within 3-5 days"),
    ("Cantaloupe",          "Produce", "Fridge", 3, 5, 7, "Cut only; whole uncut lasts 2-3 days at room temp"),
    ("Pineapple",           "Produce", "Fridge", 3, 5, 7, "Cut only"),
    ("Pineapple",           "Produce", "Pantry",  2,  3,  5,  "Whole, uncut"),
    ("Tomatoes",            "Produce", "Pantry",  5,  7,  10, "Refrigerating dulls flavor"),
    ("Cherry Tomatoes",     "Produce", "Fridge",  5,  7,  10, None),
    ("Onions",              "Produce", "Pantry",  14, 30, 60, "Keep dry and dark"),
    ("Garlic",              "Produce", "Pantry",  14, 30, 60, "Whole head"),
    ("Potatoes",            "Produce", "Pantry",  14, 21, 30, "Keep away from light"),
    ("Sweet Potatoes",      "Produce", "Pantry",  14, 21, 30, None),
    ("Carrots",             "Produce", "Fridge",  14, 21, 30, None),
    ("Broccoli",            "Produce", "Fridge",  3,  5,  7,  None),
    ("Cauliflower",         "Produce", "Fridge",  5,  7,  10, None),
    ("Cabbage",             "Produce", "Fridge",  14, 21, 30, None),
    ("Spinach",             "Produce", "Fridge",  3,  5,  7,  None),
    ("Lettuce",             "Produce", "Fridge",  5,  7,  10, None),
    ("Cucumber",            "Produce", "Fridge",  5,  7,  10, None),
    ("Bell Peppers",        "Produce", "Fridge",  5,  7,  14, None),
    ("Jalapeños",           "Produce", "Fridge",  5,  7,  14, None),
    ("Green Chillies",      "Produce", "Fridge",  5,  7,  14, "Common in Pakistani/Indian cooking"),
    ("Coriander",           "Produce", "Fridge",  5,  7,  10, "Also called cilantro"),
    ("Mint",                "Produce", "Fridge",  5,  7,  10, None),
    ("Green Onions",        "Produce", "Fridge",  5,  7,  10, None),
    ("Celery",              "Produce", "Fridge",  14, 21, 28, None),
    ("Mushrooms",           "Produce", "Fridge",  5,  7,  10, None),
    ("Zucchini",            "Produce", "Fridge",  5,  7,  10, None),
    ("Eggplant",            "Produce", "Fridge",  5,  7,  10, "Also called brinjal/baingan"),
    ("Corn",                "Produce", "Fridge",  1,  2,  3,  "Best eaten day of purchase"),
    ("Peas",                "Produce", "Fridge",  3,  5,  7,  "In pod; shelled peas last 3-5 days"),
    ("Green Beans",         "Produce", "Fridge",  3,  5,  7,  None),
    ("Passionfruit",        "Produce", "Fridge", 3, 5, 7, "Best when wrinkled"),
    ("Dragonfruit",         "Produce", "Fridge",  4,  6,  8,   None),
    ("Starfruit",           "Produce", "Fridge",  5,  7,  10,  None),
    ("Persimmons",          "Produce", "Pantry", 3, 5, 10, "Ripen at room temp; refrigerate once ripe for up to 2 months"),
    ("Cherries",            "Produce", "Fridge",  5,  7,  10,  None),
    ("Apricots",            "Produce", "Fridge", 5, 7, 10, None),
    ("Plums",               "Produce", "Fridge",  5,  7,  10,  None),
    ("Kale",                "Produce", "Fridge",  5,  7,  10,  None),
    ("Asparagus",           "Produce", "Fridge", 2, 3, 5, "Store upright in water for best results"),
    ("Okra",                "Produce", "Fridge", 2, 3, 5, "Ladyfinger; common in South Asia"),
    ("Pears",               "Produce", "Fridge",  3,  5,  7,   "Ripe; unripe ripen at room temp first"),
    ("Pears",               "Produce", "Pantry",  2,  4,  7,   "Until ripe only"),
    ("Peaches",             "Produce", "Fridge",  3,  5,  7,   "Ripe; ripen at room temp first"),
    ("Nectarines",          "Produce", "Fridge",  3,  5,  7,   None),
    ("Kiwi",                "Produce", "Fridge",  5,  14, 21,  "Ripe; unripe ripen at room temp"),
    ("Figs",                "Produce", "Fridge",  2,  3,  5,   "Very perishable"),
    ("Dates",               "Produce", "Pantry",  30, 90, 180, "Soft dates; Medjool etc."),
    ("Dates",               "Produce", "Fridge",  90, 180,365, "Extends life significantly"),
    ("Coconut",             "Produce", "Pantry",  7,  14, 21,  "Whole unopened"),
    ("Coconut",             "Produce", "Fridge",  3,  5,  7,   "Cracked/opened"),
    ("Lychee",              "Produce", "Fridge",  3,  5,  7,   "In shell; very perishable"),
    ("Jackfruit",           "Produce", "Fridge",  3,  5,  7,   "Cut; whole unripe can sit at room temp"),
    ("Bitter Melon",        "Produce", "Fridge",  3,  5,  7,   "Karela; common in South Asian cooking"),
    ("Bottle Gourd",        "Produce", "Fridge",  5,  7,  10,  "Lauki/Doodhi; popular in Pakistan/India"),
    ("Tinda",               "Produce", "Fridge",  3,  5,  7,   "Indian round gourd; very common in Pakistani markets"),
    ("Ridge Gourd",         "Produce", "Fridge",  3,  5,  7,   "Turai/Luffa; common in South Asia"),
    ("Drumstick",           "Produce", "Fridge",  3,  5,  7,   "Moringa pods; popular in South Asian cooking"),
    ("Arvi",                "Produce", "Pantry",  7,  14, 21,  "Taro root; common in Pakistani cooking"),
    ("Turnip",              "Produce", "Fridge",  7,  14, 21,  "Shalgam; popular in South Asian cuisine"),
    ("Radish",              "Produce", "Fridge",  5,  7,  14,  "Mooli; common in Pakistani salads"),
    ("Beetroot",            "Produce", "Fridge",  7,  14, 21,  None),
    ("Leek",                "Produce", "Fridge",  7,  10, 14,  None),
    ("Fennel Bulb",         "Produce", "Fridge",  5,  7,  10,  None),
    ("Artichoke",           "Produce", "Fridge",  5,  7,  10,  None),
    ("Brussels Sprouts",    "Produce", "Fridge",  3,  5,  7,   None),
    ("Bok Choy",            "Produce", "Fridge",  3,  5,  7,   None),
    ("Swiss Chard",         "Produce", "Fridge",  3,  5,  7,   None),
    ("Arugula",             "Produce", "Fridge",  3,  5,  7,   None),
    ("Watercress",          "Produce", "Fridge",  2,  3,  5,   None),
    ("Endive",              "Produce", "Fridge",  3,  5,  7,   None),
    ("Butternut Squash",    "Produce", "Pantry",  30, 60, 90,  "Whole; cut refrigerate and use in 5-7 days"),
    ("Pumpkin",             "Produce", "Pantry",  30, 60, 90,  "Whole; cut refrigerate"),
    ("Ginger",              "Produce", "Fridge",  21, 30, 45,  "Fresh root; freeze for up to 6 months"),
    ("Turmeric Root",       "Produce", "Fridge",  14, 21, 30,  "Fresh haldi; freeze for longer"),
    ("Lemongrass",          "Produce", "Fridge",  7,  14, 21,  None),
    ("Dill",                "Produce", "Fridge",  3,  5,  7,   None),
    ("Parsley",             "Produce", "Fridge",  5,  7,  10,  None),
    ("Basil",               "Produce", "Pantry",  5,  7,  10,  "Keep at room temp in water like flowers; fridge blackens it"),
    ("Thyme",               "Produce", "Fridge",  7,  10, 14,  "Fresh"),
    ("Rosemary",            "Produce", "Fridge",  7,  10, 14,  "Fresh"),
    ("Chives",              "Produce", "Fridge",  5,  7,  10,  None),
    ("Oregano",             "Produce", "Fridge",  5,  7,  10,  "Fresh"),
    ("Curry Leaves",        "Produce", "Fridge",  5,  7,  14,  "Kari patta; essential in South Asian cooking"),
    ("Fenugreek Leaves",    "Produce", "Fridge",  3,  5,  7,   "Methi; used fresh or dried in Pakistani cooking"),
    ("Pomelo",              "Produce", "Fridge",  7,  14, 21,  None),
    ("Tamarind",            "Produce", "Pantry",  30, 90, 180, "Imli; block form; paste refrigerate after opening"),
    ("Amla",                "Produce", "Fridge",  5,  7,  14,  "Indian gooseberry; very common in South Asia"),
    ("Ber",                 "Produce", "Fridge",  3,  5,  7,   "Jujube/Chinese date; popular seasonal fruit in Pakistan"),
    ("Falsa",               "Produce", "Fridge",  1,  2,  3,   "Grewia berries; very perishable summer fruit in Pakistan"),
    ("Chikoo",              "Produce", "Fridge",  3,  5,  7,   "Sapodilla; popular in Pakistan/South Asia"),
    ("Karonda",             "Produce", "Fridge",  3,  5,  7,   "Natal plum; used in chutneys in South Asia"),


    # ── DAIRY ────────────────────────────────────────────────────────────────────
    ("Whole Milk",          "Dairy",   "Fridge",  5,  7,  10, "After opening; check sell-by"),
    ("Skim Milk",           "Dairy",   "Fridge",  5,  7,  10, None),
    ("Full Cream Milk",     "Dairy",   "Fridge",  5,  7,  10, "Common in Pakistani/international markets"),
    ("UHT Milk",            "Dairy",   "Pantry",  60, 90, 180,"Unopened; once opened refrigerate and use in 7 days"),
    ("Half and Half",       "Dairy",   "Fridge",  5,  7,  10, None),
    ("Heavy Cream",         "Dairy",   "Fridge",  5,  7,  14, None),
    ("Butter",              "Dairy",   "Fridge", 21, 30, 45, "Salted lasts longer than unsalted"),
    ("Butter",              "Dairy",   "Freezer", 60, 90, 180,None),
    ("Cheddar Cheese",      "Dairy",   "Fridge",  14, 21, 30, "Opened block"),
    ("Mozzarella Cheese",   "Dairy",   "Fridge",  5,  7,  14, "Fresh; sliced or shredded"),
    ("Cream Cheese",        "Dairy",   "Fridge",  7,  14, 21, "Opened"),
    ("Cottage Cheese",      "Dairy",   "Fridge",  5,  7,  10, "Opened"),
    ("Greek Yogurt",        "Dairy",   "Fridge",  7,  14, 21, None),
    ("Plain Yogurt",        "Dairy",   "Fridge",  7,  14, 21, None),
    ("Dahi",                "Dairy",   "Fridge",  3,  5,  7,  "Pakistani-style fresh yogurt; shorter life than commercial"),
    ("Lassi",               "Dairy",   "Fridge",  2,  3,  5,  "Fresh-made; unopened commercial lasts longer"),
    ("Paneer",              "Dairy",   "Fridge",  3,  5,  7,  "Fresh Indian/Pakistani cheese; freeze for longer"),
    ("Paneer",              "Dairy",   "Freezer", 30, 60, 90, None),
    ("Eggs",                "Dairy",   "Fridge",  21, 35, 45, "From purchase date; USDA recommends refrigerating"),
    ("Sour Cream",          "Dairy",   "Fridge",  7,  14, 21, "Opened"),
    ("Whipped Cream",       "Dairy", "Fridge", 5, 7, 10, "Opened aerosol can; fresh whipped cream only 1-2 days"),
    ("Condensed Milk",      "Dairy", "Pantry", 270, 365, 730, "Unopened; refrigerate after opening, use in 14 days"),
    ("Brie Cheese",         "Dairy",   "Fridge",  7,  14, 21,  "Soft-ripened"),
    ("Feta Cheese",         "Dairy",   "Fridge",  5,  7,  14,  "In brine"),
    ("Ricotta Cheese",      "Dairy",   "Fridge",  5,  7,  10,  None),
    ("Evaporated Milk",     "Dairy", "Pantry", 270, 365, 730, "Unopened; refrigerate after opening, use in 5-7 days"),
    ("Kefir",               "Dairy", "Fridge", 7, 14, 21, "Fermented milk drink; check sell-by"),
    ("Buttermilk",          "Dairy",   "Fridge",  7,  10, 14,  None),
    ("Camembert",           "Dairy",   "Fridge",  7,  14, 21,  "Soft French cheese"),
    ("Parmesan Cheese",     "Dairy",   "Fridge",  21, 30, 45,  "Hard cheese block, opened"),
    ("Gouda Cheese",        "Dairy",   "Fridge",  14, 21, 30,  "Opened block"),
    ("Swiss Cheese",        "Dairy",   "Fridge",  14, 21, 28,  "Sliced"),
    ("Provolone",           "Dairy",   "Fridge",  14, 21, 28,  "Sliced"),
    ("Processed Cheese",    "Dairy",   "Fridge",  14, 21, 30,  "e.g. Kraft singles; unopened up to best-by"),
    ("Khoya",               "Dairy",   "Fridge",  5,  7,  10,  "Mawa; reduced milk solid used in Pakistani/Indian sweets"),
    ("Khoya",               "Dairy",   "Freezer", 30, 60, 90,  None),
    ("Cream",               "Dairy",   "Fridge",  5,  7,  10,  "Fresh dairy cream; opened"),
    ("Malai",               "Dairy",   "Fridge",  2,  3,  5,   "Fresh milk fat/clotted cream; common in Pakistani tea culture"),
    ("Labneh",              "Dairy",   "Fridge",  7,  14, 21,  "Strained yogurt cheese; popular in Middle East/Pakistan"),
    ("Shrikhand",           "Dairy",   "Fridge",  3,  5,  7,   "Sweetened strained yogurt dessert"),
    ("Raita",               "Dairy",   "Fridge",  1,  2,  3,   "Yogurt-based condiment; prepared"),

    # ── MEAT ─────────────────────────────────────────────────────────────────────
    ("Chicken Breast",      "Meat",    "Fridge",  1,  2,  3,  "Raw; cook or freeze within 2 days"),
    ("Chicken Breast",      "Meat",    "Freezer", 180,270,365,None),
    ("Chicken Thighs",      "Meat",    "Fridge",  1,  2,  3,  None),
    ("Chicken Thighs",      "Meat",    "Freezer", 180,270,365,None),
    ("Whole Chicken",       "Meat",    "Fridge",  1,  2,  3,  None),
    ("Whole Chicken",       "Meat",    "Freezer", 270,365,365,None),
    ("Minced Chicken",      "Meat",    "Fridge",  1,  2,  2,  "Also called chicken qeema"),
    ("Minced Chicken",      "Meat",    "Freezer", 90, 120,180,None),
    ("Ground Beef",         "Meat",    "Fridge",  1,  2,  2,  None),
    ("Ground Beef",         "Meat",    "Freezer", 90, 120,180,None),
    ("Beef Steak",          "Meat", "Fridge", 3, 4, 5, None),
    ("Beef Steak",          "Meat",    "Freezer", 180,270,365,None),
    ("Minced Beef",         "Meat",    "Fridge",  1,  2,  2,  "Also called beef qeema / keema"),
    ("Minced Beef",         "Meat",    "Freezer", 90, 120,180,None),
    ("Mutton",              "Meat",    "Fridge",  2,  3,  5,  "Common in Pakistani/Middle Eastern markets"),
    ("Mutton",              "Meat",    "Freezer", 180,270,365,None),
    ("Lamb Chops",          "Meat",    "Fridge",  2,  3,  5,  None),
    ("Lamb Chops",          "Meat",    "Freezer", 180,270,365,None),
    ("Pork Chops",          "Meat",    "Fridge",  2,  3,  5,  None),
    ("Pork Chops",          "Meat",    "Freezer", 120,180,365,None),
    ("Bacon",               "Meat",    "Fridge",  5, 7, 7, "Opened package; USDA recommends use within 7 days"),
    ("Bacon",               "Meat",    "Freezer", 30, 60, 90, None),
    ("Salmon",              "Meat",    "Fridge",  1,  2,  3,  "Raw fillet"),
    ("Salmon",              "Meat",    "Freezer", 90, 180,270,None),
    ("Tuna Steak",          "Meat",    "Fridge",  1,  2,  2,  "Raw"),
    ("Tuna Steak",          "Meat",    "Freezer", 90, 180,270,None),
    ("Shrimp",              "Meat",    "Fridge",  1,  2,  3,  "Raw, peeled"),
    ("Shrimp",              "Meat",    "Freezer", 90, 180,270,None),    
    ("Deli Ham",            "Meat",    "Fridge",  3, 4, 5, "Sliced, opened package; USDA recommends 3-5 days"),
    ("Deli Turkey",         "Meat",    "Fridge",  3, 4, 5, "Sliced, opened package"),
    ("Sausages",            "Meat",    "Fridge",  3,  5,  7,  "Uncooked, opened"),
    ("Sausages",            "Meat",    "Freezer", 30, 60, 90, None),
    ("Hot Dogs",            "Meat",    "Fridge",  5, 7, 7, "Opened package; USDA recommends within 1 week"),
    ("Seekh Kebab",         "Meat",    "Fridge",  1,  2,  3,  "Raw; common in Pakistani/South Asian markets"),
    ("Seekh Kebab",         "Meat",    "Freezer", 30, 60, 90, None),
    ("Turkey Breast",       "Meat",    "Fridge",  2,  3,  5,   None),
    ("Duck Legs",           "Meat",    "Fridge",  2,  3,  5,   None),
    ("Venison",             "Meat",    "Fridge",  2,  3,  5,   "Game meat"),
    ("Goat Meat",           "Meat",    "Fridge",  2,  3,  5,   None),
    ("Crab",                "Meat",    "Fridge",  1,  2,  3,   "Raw"),
    ("Lobster",             "Meat",    "Fridge",  1,  2,  3,   None),
    ("Clams",               "Meat",    "Fridge",  1,  2,  3,   None),
    ("Oysters",             "Meat",    "Fridge",  3, 5, 7, "Live in shell; shucked use within 2 days"),
    ("Chicken Wings",       "Meat",    "Fridge",  1,  2,  3,   "Raw"),
    ("Chicken Wings",       "Meat",    "Freezer", 180,270,365, None),
    ("Chicken Drumsticks",  "Meat",    "Fridge",  1,  2,  3,   "Raw"),
    ("Chicken Drumsticks",  "Meat",    "Freezer", 180,270,365, None),
    ("Chicken Liver",       "Meat",    "Fridge",  1,  2,  2,   "Raw; organ meat spoils fastest"),
    ("Chicken Liver",       "Meat",    "Freezer", 90, 120,180, None),
    ("Beef Ribs",           "Meat",    "Fridge",  3,  4,  5,   "Raw"),
    ("Beef Ribs",           "Meat",    "Freezer", 180,270,365, None),
    ("Beef Liver",          "Meat",    "Fridge",  1,  2,  2,   "Raw; use immediately"),
    ("Beef Liver",          "Meat",    "Freezer", 90, 120,180, None),
    ("Lamb Mince",          "Meat",    "Fridge",  1,  2,  2,   "Raw ground lamb"),
    ("Lamb Mince",          "Meat",    "Freezer", 90, 120,180, None),
    ("Nihari Meat",         "Meat",    "Fridge",  2,  3,  4,   "Cooked slow-braised beef/lamb; popular in Pakistani cuisine"),
    ("Koftay",              "Meat",    "Fridge",  1,  2,  3,   "Raw meatballs; freeze immediately if not cooking same day"),
    ("Koftay",              "Meat",    "Freezer", 60, 90, 120, None),
    ("Fish (generic)",      "Meat",    "Fridge",  1,  2,  3,   "Raw whole or fillet; use or freeze ASAP"),
    ("Fish (generic)",      "Meat",    "Freezer", 90, 180,270, None),
    ("Tilapia",             "Meat",    "Fridge",  1,  2,  3,   "Raw fillet"),
    ("Tilapia",             "Meat",    "Freezer", 90, 180,270, None),
    ("Catfish",             "Meat",    "Fridge",  1,  2,  3,   "Rohu/Catla also apply; popular in Pakistani river fish"),
    ("Catfish",             "Meat",    "Freezer", 90, 180,270, None),
    ("Rohu",                "Meat",    "Fridge",  1,  2,  3,   "Major freshwater fish in Pakistan"),
    ("Rohu",                "Meat",    "Freezer", 60, 90, 180, None),
    ("Scallops",            "Meat",    "Fridge",  1,  2,  2,   "Raw; very perishable"),
    ("Scallops",            "Meat",    "Freezer", 90, 180,270, None),
    ("Squid",               "Meat",    "Fridge",  1,  2,  3,   "Raw"),
    ("Squid",               "Meat",    "Freezer", 90, 180,270, None),
    ("Cooked Chicken",      "Meat",    "Fridge",  3,  4,  5,   "Any preparation; USDA 3-4 days"),
    ("Cooked Beef",         "Meat",    "Fridge",  3,  4,  5,   "Cooked; USDA 3-4 days"),
    ("Cooked Fish",         "Meat",    "Fridge",  2,  3,  4,   "Any preparation"),
    ("Cooked Shrimp",       "Meat",    "Fridge",  2,  3,  4,   None),
    ("Pepperoni",           "Meat",    "Fridge",  14, 21, 30,  "Opened package; cured"),
    ("Salami",              "Meat",    "Fridge",  14, 21, 30,  "Opened; dry-cured"),
    ("Chorizo",             "Meat",    "Fridge",  5,  7,  14,  "Fresh uncooked; dry-cured lasts longer"),

    # ── PANTRY ───────────────────────────────────────────────────────────────────
    ("Bread",               "Pantry", "Pantry", 3, 5, 7, "Room temp; refrigerating extends life but stales faster"),
    ("Whole Wheat Bread",   "Pantry",  "Pantry",  5,  7,  10, None),
    ("Pita Bread",          "Pantry",  "Pantry",  5,  7,  10, None),
    ("Pasta",               "Pantry",  "Pantry",  365,730,1095,"Dry, unopened"),
    ("Rice",                "Pantry",  "Pantry",  365,730,1095,"White rice; unopened"),
    ("Basmati Rice",        "Pantry",  "Pantry",  365,730,1095,"Aromatic long-grain; common in South Asian cooking"),
    ("Oats",                "Pantry",  "Pantry",  180,365,730, "Sealed container"),
    ("Flour",               "Pantry",  "Pantry",  90, 180,365, "All-purpose; sealed"),
    ("Atta Flour",          "Pantry",  "Pantry",  60, 90, 180, "Whole wheat flour used for roti; shorter shelf life due to higher oil content"),
    ("Maida",               "Pantry",  "Pantry",  90, 180,365, "Refined flour; used in Pakistani/Indian baking"),
    ("Sugar",               "Pantry",  "Pantry",  730,1825,3650,"Indefinite if kept dry"),
    ("Salt",                "Pantry",  "Pantry",  1825,3650,3650,"Indefinite"),
    ("Olive Oil",           "Pantry",  "Pantry",  365,540,730, "Opened; store away from heat and light"),
    ("Vegetable Oil",       "Pantry",  "Pantry",  365,540,730, "Opened"),
    ("Cooking Oil",         "Pantry",  "Pantry",  180,365,540, "Generic; refined oils last longer"),
    ("Soy Sauce",           "Pantry",  "Fridge", 180, 365, 1095, "After opening; keeps well due to high sodium"),
    ("Ketchup",             "Pantry",  "Fridge",   60, 120, 180, "After opening; unopened pantry 1 year"),
    ("Mayonnaise",          "Pantry",  "Fridge", 30, 60, 60, "After opening; always refrigerate"),
    ("Mustard",             "Pantry",  "Fridge", 90, 180, 365, "After opening"),
    ("Hot Sauce",           "Pantry",  "Fridge",  90, 180,365, "After opening"),
    ("Vinegar",             "Pantry",  "Pantry",  730,1825,3650,"Practically indefinite"),
    ("Honey",               "Pantry",  "Pantry",  730,3650,3650,"Indefinite if sealed"),
    ("Peanut Butter",       "Pantry",  "Pantry", 30, 60, 90, "Natural opened; commercial opened in pantry up to 3 months, fridge up to 6"),
    ("Jam",                 "Pantry",  "Fridge", 30, 90, 180, "After opening; discard if mold appears"),
    ("Tomato Sauce",        "Pantry",  "Fridge",  5,  7,  10, "Opened jar"),
    ("Tomato Paste",        "Pantry",  "Fridge", 5, 7, 10, "Opened can — transfer to airtight container"),
    ("Coconut Milk",        "Pantry",  "Fridge",  4,  5,  7,  "Opened can; transfer to airtight container"),
    ("Chicken Broth",       "Pantry",  "Fridge",  3,  4,  5,  "Opened carton"),
    ("Canned Chickpeas",    "Pantry",  "Fridge",  3,  4,  5,  "Opened can; transfer to airtight container"),
    ("Canned Tomatoes",     "Pantry",  "Fridge",  3,  4,  5,  "Opened can"),
    ("Canned Tuna",         "Pantry",  "Fridge",  3,  4,  5,  "Opened can"),
    ("Lentils",             "Pantry",  "Pantry",  365,730,1095,"Dry; sealed"),
    ("Chickpeas",           "Pantry",  "Pantry",  365,730,1095,"Dry; sealed. Also called chana"),
    ("Black Beans",         "Pantry",  "Pantry",  365,730,1095,"Dry; sealed"),
    ("Masoor Dal",          "Pantry",  "Pantry",  365,730,1095,"Red lentils; common in Pakistani cooking"),
    ("Chana Dal",           "Pantry",  "Pantry",  365,730,1095,"Split chickpeas"),
    ("Moong Dal",           "Pantry",  "Pantry",  365,730,1095,"Split mung beans"),
    ("Urad Dal",            "Pantry",  "Pantry",  365,730,1095,"Black gram lentils"),
    ("Couscous",            "Pantry",  "Pantry",  365,730,1095,"Dry, sealed"),
    ("Millet",              "Pantry",  "Pantry",  365,730,1095,"Dry grain"),
    ("Barley",              "Pantry",  "Pantry",  365,730,1095,"Dry grain"),
    ("Rye Flour",           "Pantry",  "Pantry",  90, 180,365, "Sealed"),
    ("Brown Sugar",         "Pantry",  "Pantry",  365,730,1095,"Keep airtight"),
    ("Maple Syrup",         "Pantry",  "Fridge",  180,365,730, "After opening"),
    ("Tahini",              "Pantry",  "Fridge",  90, 180,270, "Sesame paste"),
    ("Molasses",            "Pantry",  "Pantry",  365,730,1095,"Sealed jar"),
    ("Coconut Oil",         "Pantry",  "Pantry",  365,540,730, "Solidifies below 24°C"),
    ("Quinoa",              "Pantry",  "Pantry",  365,730,1095,"Dry, sealed"),
    ("Cornmeal",            "Pantry",  "Pantry",  90, 180,365, "Sealed; whole grain cornmeal shorter life"),
    ("Semolina",            "Pantry",  "Pantry",  180,365,730, "Sooji/rava; used in Pakistani halwa and upma"),
    ("Vermicelli",          "Pantry",  "Pantry",  180,365,730, "Seviyan; dry; used in Pakistani sewain/kheer"),
    ("Bread Crumbs",        "Pantry",  "Pantry",  90, 180,270, "Dry, sealed"),
    ("Corn Starch",         "Pantry",  "Pantry",  365,730,1095,"Sealed; indefinite if dry"),
    ("Baking Powder",       "Pantry",  "Pantry",  180,270,365, "Loses potency after 6-12 months; test before use"),
    ("Baking Soda",         "Pantry",  "Pantry",  180,365,730, "For baking; odor absorber use replace every 30 days"),
    ("Yeast (Dry)",         "Pantry",  "Pantry",  90, 180,365, "Unopened; refrigerate after opening for up to 4 months"),
    ("Vanilla Extract",     "Pantry",  "Pantry",  365,1095,1825,"Pure extract; imitation lasts 2-4 years"),
    ("Cinnamon (Ground)",   "Pantry",  "Pantry",  365,730,1095,"Loses potency but stays safe"),
    ("Cumin (Ground)",      "Pantry",  "Pantry",  365,730,1095,"Zeera; essential in Pakistani cooking"),
    ("Cumin Seeds",         "Pantry",  "Pantry",  365,730,1825,"Whole seeds last longer than ground"),
    ("Coriander (Ground)",  "Pantry",  "Pantry",  365,730,1095,"Dhania powder"),
    ("Turmeric (Ground)",   "Pantry",  "Pantry",  365,730,1095,"Haldi; anti-caking agents extend shelf life"),
    ("Red Chilli Powder",   "Pantry",  "Pantry",  365,730,1095,"Lal mirch; staple in Pakistani cooking"),
    ("Garam Masala",        "Pantry",  "Pantry",  180,365,730, "Ground blend; loses aroma faster than whole spices"),
    ("Chaat Masala",        "Pantry",  "Pantry",  180,365,730, "Pakistani/Indian spice blend"),
    ("Black Pepper",        "Pantry",  "Pantry",  365,730,1095,"Ground; whole peppercorns last longer"),
    ("Cardamom",            "Pantry",  "Pantry",  365,730,1095,"Elaichi; whole pods keep aroma longer than ground"),
    ("Cloves",              "Pantry",  "Pantry",  365,730,1095,"Laung; whole"),
    ("Bay Leaves",          "Pantry",  "Pantry",  365,730,1095,"Tezpatta; dried"),
    ("Nutmeg",              "Pantry",  "Pantry",  365,730,1095,"Whole lasts up to 4 years; ground 2-3 years"),
    ("Paprika",             "Pantry",  "Pantry",  365,730,1095,"Ground"),
    ("Dried Fenugreek",     "Pantry",  "Pantry",  180,365,730, "Kasuri methi; popular in Pakistani dishes"),
    ("Star Anise",          "Pantry",  "Pantry",  365,730,1825,"Whole; used in biryani and nihari"),
    ("Sesame Seeds",        "Pantry",  "Pantry",  180,365,730, "Til; can go rancid; store in cool dark place"),
    ("Poppy Seeds",         "Pantry",  "Pantry",  90, 180,365, "Khas khas; high oil content; prone to rancidity"),
    ("Dried Red Chillies",  "Pantry",  "Pantry",  180,365,730, "Sabut lal mirch; whole dried"),
    ("Tamarind Paste",      "Pantry",  "Fridge",  90, 180,270, "Imli paste; after opening"),
    ("Mango Powder",        "Pantry",  "Pantry",  180,365,730, "Amchur; dried green mango powder"),
    ("Pomegranate Powder",  "Pantry",  "Pantry",  180,365,730, "Anardana; used in Pakistani chutneys"),
    ("Rose Water",          "Pantry",  "Pantry",  180,365,730, "Gulab jal; used in Pakistani desserts"),
    ("Kewra Water",         "Pantry",  "Pantry",  180,365,730, "Pandanus extract; used in Pakistani sweets and biryani"),
    ("Food Coloring",       "Pantry",  "Pantry",  365,1095,1825,"Liquid or gel; stays potent for years"),
    ("Dried Apricots",      "Pantry",  "Pantry",  90, 180,365, "Khurmani; common dry fruit in Pakistan"),
    ("Dried Mango",         "Pantry",  "Pantry",  90, 180,365, "Slices; sealed"),
    ("Raisins",             "Pantry",  "Pantry",  90, 180,365, "Kishmish; sealed package"),
    ("Sultanas",            "Pantry",  "Pantry",  90, 180,365, "Golden raisins"),
    ("Prunes",              "Pantry",  "Pantry",  90, 180,365, "Dried plums"),
    ("Dried Cranberries",   "Pantry",  "Pantry",  90, 180,365, None),
    ("Almonds",             "Pantry",  "Pantry",  90, 180,365, "Badam; shelled; unsealed can go rancid"),
    ("Walnuts",             "Pantry",  "Pantry",  90, 180,365, "Akhrot; high oil content; fridge extends life"),
    ("Cashews",             "Pantry",  "Pantry",  90, 180,365, "Kaju; sealed"),
    ("Pistachios",          "Pantry",  "Pantry",  90, 180,365, "Pista; in shell last longer"),
    ("Peanuts",             "Pantry",  "Pantry",  60, 90, 180, "Shelled roasted; prone to rancidity"),
    ("Pine Nuts",           "Pantry",  "Pantry",  30, 60, 90,  "Chilgoza; high oil content; very prone to rancidity"),
    ("Flaxseeds",           "Pantry",  "Pantry",  90, 180,365, "Alsi; whole seeds last longer than ground"),
    ("Chia Seeds",          "Pantry",  "Pantry",  365,730,1095,"Sealed; very stable"),
    ("Sunflower Seeds",     "Pantry",  "Pantry",  90, 180,365, "Shelled, roasted"),
    ("Pumpkin Seeds",       "Pantry",  "Pantry",  90, 180,365, "Shelled, roasted"),
    ("Canned Beans",        "Pantry",  "Fridge",  3,  4,  5,   "Any variety; opened can — transfer to container"),
    ("Canned Corn",         "Pantry",  "Fridge",  3,  4,  5,   "Opened can"),
    ("Canned Lentils",      "Pantry",  "Fridge",  3,  4,  5,   "Opened can"),
    ("Canned Salmon",       "Pantry",  "Fridge",  3,  4,  5,   "Opened can"),
    ("Canned Sardines",     "Pantry",  "Fridge",  3,  4,  5,   "Opened can"),
    ("Fish Sauce",          "Pantry",  "Fridge",  180,365,730, "After opening; high salt content preserves it"),
    ("Oyster Sauce",        "Pantry",  "Fridge",  90, 180,365, "After opening"),
    ("Hoisin Sauce",        "Pantry",  "Fridge",  90, 180,365, "After opening"),
    ("Sriracha",            "Pantry",  "Fridge",  90, 180,365, "After opening"),
    ("Chilli Garlic Sauce", "Pantry",  "Fridge",  90, 180,365, "After opening; popular in Pakistan"),
    ("BBQ Sauce",           "Pantry",  "Fridge",  30, 90, 180, "After opening"),
    ("Teriyaki Sauce",      "Pantry",  "Fridge",  30, 90, 180, "After opening"),
    ("Pickle (Achar)",      "Pantry",  "Pantry",  180,365,730, "Oil-based Pakistani/Indian mango or mixed pickle; sealed"),
    ("White Vinegar",       "Pantry",  "Pantry",  730,1825,3650,"Practically indefinite"),
    ("Apple Cider Vinegar", "Pantry",  "Pantry",  730,1825,3650,"Raw/filtered; indefinite"),
    ("Balsamic Vinegar",    "Pantry",  "Pantry",  1095,1825,3650,"Gets better with age"),
    ("Worcestershire Sauce","Pantry",  "Fridge",  365,730,1095,"After opening"),
    ("Ghee",                "Pantry",  "Pantry",  90, 180,365, "Clarified butter; sealed; traditional preservation method"),
    ("Ghee",                "Pantry",  "Fridge",  180,365,730, "Refrigerated extends life significantly"),
    ("Almond Butter",       "Pantry",  "Fridge",  90, 180,270, "Natural; opened"),
    ("Sunflower Butter",    "Pantry",  "Pantry",  90, 180,270, "Opened"),
    ("Nutella",             "Pantry",  "Pantry",  30, 90, 180, "Opened jar"),
    ("Cream of Tartar",     "Pantry",  "Pantry",  365,730,1095,"Indefinite if sealed"),
    ("Gelatin",             "Pantry",  "Pantry",  365,730,1095,"Dry, sealed"),
    ("Powdered Sugar",      "Pantry",  "Pantry",  365,730,1095,"Sealed; no expiry if dry"),
    ("Cocoa Powder",        "Pantry",  "Pantry",  365,730,1095,"Unsweetened; sealed"),
    ("Chocolate Chips",     "Pantry",  "Pantry",  180,365,730, "Sealed bag"),
    ("Desiccated Coconut",  "Pantry",  "Pantry",  90, 180,365, "Dried shredded coconut; sealed"),
    ("Tomato Ketchup Sachet","Pantry", "Pantry",  180,365,365, "Single-serve packet"),
    ("Beef Stock Cube",     "Pantry",  "Pantry",  180,365,730, "Bouillon cube; sealed"),
    ("Chicken Stock Cube",  "Pantry",  "Pantry",  180,365,730, "Bouillon cube"),
    ("Vegetable Stock",     "Pantry",  "Fridge",  3,  4,  5,   "Opened carton"),
    ("Beef Broth",          "Pantry",  "Fridge",  3,  4,  5,   "Opened carton"),
    ("Miso Paste",          "Pantry",  "Fridge",  90, 180,365, "After opening; fermented; very long life"),
    ("Noodles (Dry)",       "Pantry",  "Pantry",  365,730,1095,"Any variety; sealed"),
    ("Glass Noodles",       "Pantry",  "Pantry",  365,730,1095,"Cellophane/bean thread noodles"),
    ("Rice Noodles",        "Pantry",  "Pantry",  365,730,1095,"Dry"),
    ("Instant Noodles",     "Pantry",  "Pantry",  180,365,730, "e.g. Maggi, Knorr; check best-by"),
    ("Popcorn Kernels",     "Pantry",  "Pantry",  180,365,730, "Dry; sealed"),
    ("Biryani Masala",      "Pantry",  "Pantry",  180,365,730, "Packaged spice blend"),
    ("Nihari Masala",       "Pantry",  "Pantry",  180,365,730, "Packaged spice blend; popular in Pakistan"),
    ("Haleem Mix",          "Pantry",  "Pantry",  180,365,730, "Dry spice and grain mix"),
    ("Paya Masala",         "Pantry",  "Pantry",  180,365,730, "Trotters spice blend"),
    ("Tikka Masala",        "Pantry",  "Pantry",  180,365,730, "Spice blend"),
    ("Karahi Masala",       "Pantry",  "Pantry",  180,365,730, "Pakistani/Indian spice blend"),
    ("Tandoori Masala",     "Pantry",  "Pantry",  180,365,730, None),
    

    # ── FROZEN ───────────────────────────────────────────────────────────────────
    ("Frozen Peas",             "Frozen",  "Freezer", 180,270,365, "Keep sealed to prevent freezer burn"),
    ("Frozen Corn",             "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Spinach",          "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Mixed Veg",        "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Fries",            "Frozen",  "Freezer", 180,270,365, None),
    ("Ice Cream",               "Frozen",  "Freezer", 30, 60, 90,  "Opened; quality degrades after 2 months"),
    ("Frozen Pizza",            "Frozen",  "Freezer", 60, 90, 180, None),
    ("Frozen Waffles",          "Frozen",  "Freezer", 60, 90, 180, None),
    ("Frozen Strawberries",     "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Mango",            "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Broccoli",         "Frozen",  "Freezer", 180,270,365, None),
    ("Frozen Chicken Nuggets",  "Frozen","Freezer", 90, 180,270, None),
    ("Frozen Fish Fillets",     "Frozen",  "Freezer", 90, 180,270, None),
    ("Frozen Dumplings",        "Frozen",  "Freezer", 90, 180,270, None),
    ("Frozen Edamame",          "Frozen",  "Freezer", 180,270,365, "In pod"),
    ("Frozen Peas and Carrots", "Frozen","Freezer",180,270,365, "Mixed"),
    ("Frozen Onion Rings",      "Frozen",  "Freezer", 90, 180,270, None),
    ("Frozen Samosa",           "Frozen",  "Freezer", 60, 90, 180, "Uncooked frozen samosas"),
    ("Frozen Paratha",          "Frozen",  "Freezer", 30, 60, 90,  "Layered flatbread; popular Pakistani frozen item"),
    ("Frozen Shrimp",           "Frozen",  "Freezer", 90, 180,270, "Commercially frozen raw"),
    ("Frozen Beef Patties",     "Frozen",  "Freezer", 90, 180,270, "Uncooked"),
    ("Frozen Meatballs",        "Frozen",  "Freezer", 90, 180,270, "Uncooked"),
    ("Frozen Burritos",         "Frozen",  "Freezer", 60, 90, 180, None),
    ("Sorbet",                  "Frozen",  "Freezer", 30, 60, 90,  "Opened; quality declines after 1-2 months"),
    ("Frozen Yogurt",           "Frozen",  "Freezer", 30, 60, 90,  "Opened"),
    ("Frozen Puff Pastry",      "Frozen",  "Freezer", 30, 60, 90,  "Unbaked"),
    ("Kulfi",                   "Frozen",  "Freezer", 7,  14, 30,  "Pakistani/Indian ice cream; opened/homemade"),


    # ── BEVERAGES ────────────────────────────────────────────────────────────────
    ("Orange Juice",        "Beverages","Fridge", 5,  7,  10, "Opened carton"),
    ("Apple Juice",         "Beverages","Fridge", 5,  7,  10, "Opened"),
    ("Sparkling Water",     "Beverages","Pantry", 365,730,730, "Unopened; opened goes flat in 1-3 days"),
    ("Soda",                "Beverages","Pantry", 180,365,540, "Unopened; opened flat in 1-3 days"),
    ("Coffee Beans",        "Beverages","Pantry", 14, 30, 60,  "Opened bag; freeze for longer"),
    ("Ground Coffee",       "Beverages","Pantry", 7,  14, 30,  "Opened bag; goes stale quickly"),
    ("Tea Bags",            "Beverages","Pantry", 180,365,730, "Sealed; loses flavor over time"),
    ("Pineapple Juice",     "Beverages","Fridge", 5,  7,  10,  "Opened carton"),
    ("Cranberry Juice",     "Beverages","Fridge", 5,  7,  10,  None),
    ("Green Tea Leaves",    "Beverages","Pantry", 180,365,730, "Sealed"),
    ("Herbal Tea",          "Beverages","Pantry", 180,365,730, None),
    ("Instant Coffee",      "Beverages","Pantry", 365,730,1095,"Sealed jar"),
    ("Energy Drink",        "Beverages","Pantry", 180,365,540, "Unopened"),
    ("Rooh Afza",           "Beverages","Pantry", 365,730,730, "Unopened syrup bottle; very popular in Pakistan/South Asia"),
    ("Rooh Afza",           "Beverages","Fridge", 90, 180,365, "After opening; refrigerate"),
    ("Lemon Squash",        "Beverages","Fridge", 60, 90, 180, "After opening; cordial/concentrate"),
    ("Mango Juice",         "Beverages","Fridge", 5,  7,  10,  "Opened carton/bottle"),
    ("Guava Juice",         "Beverages","Fridge", 5,  7,  10,  "Amrood ka ras; popular in Pakistan"),
    ("Sugarcane Juice",     "Beverages","Fridge", 1,  1,  2,   "Gannay ka ras; very perishable; best fresh"),
    ("Lassi (Commercial)",  "Beverages","Fridge", 5,  7,  10,  "Packaged; opened"),
    ("Coconut Water",       "Beverages","Fridge", 1,  2,  3,   "Fresh; packaged opened lasts 3-5 days"),
    ("Milk Tea Concentrate","Beverages","Fridge", 5,  7,  10,  "Doodh patti concentrate; prepared"),
    ("Kahwa",               "Beverages","Pantry", 180,365,730, "Dry green tea blend with spices; sealed"),
    ("Horchata Mix",        "Beverages","Pantry", 90, 180,365, "Dry mix"),
    ("Protein Shake (Mixed)","Beverages","Fridge",1,  2,  3,   "Pre-mixed; consume quickly"),
    ("Protein Powder",      "Beverages","Pantry", 365,540,730, "Sealed tub; opened use within 3-6 months"),
    ("Kombucha",            "Beverages","Fridge", 7,  14, 30,  "Commercial bottled; opened consume within 1 week"),
    ("Cold Brew Coffee",    "Beverages","Fridge", 7,  10, 14,  "Concentrate or ready-to-drink"),
    ("Almond Milk",         "Beverages","Fridge", 5,  7,  10,  "Opened carton"),
    ("Oat Milk",            "Beverages","Fridge", 5,  7,  10,  "Opened carton"),
    ("Soy Milk",            "Beverages","Fridge", 5,  7,  10,  "Opened carton"),
    ("Coconut Milk Drink",  "Beverages","Fridge", 5,  7,  10,  "Beverage carton; not canned cooking coconut milk"),

    # ── BAKERY ───────────────────────────────────────────────────────────────────
    ("Croissants",          "Bakery",  "Pantry", 1, 2, 2, "Fresh-baked; best day of purchase"),
    ("Bagels",              "Bakery",  "Pantry",  3,  5,  7,  None),
    ("Muffins",             "Bakery",  "Pantry",  3,  5,  7,  None),
    ("Cake",                "Bakery",  "Fridge", 3, 4, 5, "Frosted; unfrosted 1-2 days at room temp"),
    ("Scones",              "Bakery",  "Pantry",  2,  3,  5,   None),
    ("Brownies",            "Bakery",  "Pantry",  3,  5,  7,   None),
    ("Cupcakes",            "Bakery",  "Pantry",  2,  3,  5,   "Frosted"),
    ("Tarts",               "Bakery",  "Fridge",  3,  5,  7,   "Fruit-filled"),
    ("Eclairs",             "Bakery",  "Fridge",  2,  3,  5,   "Cream-filled"),
    ("Sourdough Bread",     "Bakery",  "Pantry",  3,  5,  7,   "Artisan; lasts longer than commercial due to acidity"),
    ("Baguette",            "Bakery",  "Pantry",  1,  2,  3,   "Best day of purchase"),
    ("Dinner Rolls",        "Bakery",  "Pantry",  2,  3,  5,   "Soft rolls"),
    ("Banana Bread",        "Bakery",  "Pantry",  3,  5,  7,   "Homemade loaf"),
    ("Zucchini Bread",      "Bakery",  "Pantry",  3,  5,  7,   None),
    ("Cinnamon Roll",       "Bakery",  "Pantry",  2,  3,  5,   "Frosted; refrigerate to extend"),
    ("Donuts",              "Bakery",  "Pantry",  1,  2,  3,   "Glazed or filled; best day of purchase"),
    ("Cheesecake",          "Bakery",  "Fridge",  3,  5,  7,   "Covered; homemade or commercial"),
    ("Pie Crust (unbaked)", "Bakery",  "Fridge",  2,  3,  5,   "Homemade; freeze for up to 3 months"),
    ("Puff Pastry",         "Bakery",  "Fridge",  2,  3,  5,   "Unbaked; thawed"),
    ("Ladyfingers",         "Bakery",  "Pantry",  30, 60, 90,  "Savoiardi biscuits; dry; sealed"),
    ("Sheermal",            "Bakery",  "Pantry",  1,  2,  3,   "Saffron-flavored bread; popular in Pakistan/Iran"),
    ("Kulcha",              "Bakery",  "Pantry",  1,  2,  3,   "Leavened flatbread; Pakistani/North Indian"),
    ("Chapati",             "Bakery",  "Fridge",  2,  3,  5,   "Same as roti; cooked"),
    ("Naan",                "Bakery",  "Pantry",  2,  3,  5,  "Fresh-baked; commercial packaged lasts 5-7 days"),
    ("Roti",                "Bakery",  "Pantry",  1,  2,  3,  "Fresh flatbread; freeze for longer storage"),
    ("Roti",                "Bakery",  "Freezer", 30, 60, 90, None),
    ("Paratha",             "Bakery",  "Fridge",  2,  3,  5,  "Cooked; raw dough in fridge 3-5 days"),
    ("Paratha",             "Bakery",  "Freezer", 30, 60, 90, "Cooked parathas freeze very well"),
    ("Puri",                "Bakery",  "Pantry",  1,  1,  2,  "Fried bread; best eaten fresh"),
    
    # ── SNACKS ──────────────────────────────────────────────────────────────
    ("Rice Crackers",        "Snacks",  "Pantry",  90, 120,180, "Keep sealed"),
    ("Cheese Puffs",         "Snacks",  "Pantry",  60, 90, 120, "Opened bag stales quickly"),
    ("Beef Jerky",           "Snacks",  "Pantry",  180,270,365, "Unopened; refrigerate after opening"),
    ("Fruit Leather",        "Snacks",  "Pantry",  90, 120,180, None),
    ("Roasted Chickpeas",    "Snacks",  "Pantry",  60, 90, 120, "Crunchy snack"),
    ("Seaweed Snacks",       "Snacks",  "Pantry",  90, 120,180, "Keep airtight"),
    ("Crackers",             "Snacks",  "Pantry",  90, 120,180, None),
    ("Potato Chips",         "Snacks",  "Pantry",  30, 60, 90,  "Opened bag stales quickly"),
    ("Digestive Biscuits",   "Snacks",  "Pantry",  90, 120,180, "Opened pack"),
    ("Marie Biscuits",       "Snacks",  "Pantry",  90, 120,180, "Popular in Pakistan; opened pack"),
    ("Pretzels",             "Snacks",  "Pantry",  30, 60, 90,  "Opened bag"),
    ("Popcorn (popped)",     "Snacks",  "Pantry",  1,  3,  7,   "Room temp in airtight container"),
    ("Trail Mix",            "Snacks",  "Pantry",  60, 90, 180, "With nuts and dried fruit"),
    ("Granola Bar",          "Snacks",  "Pantry",  90, 180,365, "Commercial; sealed"),
    ("Protein Bar",          "Snacks",  "Pantry",  90, 180,365, "Sealed"),
    ("Pork Rinds",           "Snacks",  "Pantry",  30, 60, 90,  "Chicharrones; opened"),
    ("Corn Chips",           "Snacks",  "Pantry",  30, 60, 90,  "Opened bag"),
    ("Nachos",               "Snacks",  "Pantry",  30, 60, 90,  "Plain chips; opened"),
    ("Rice Cakes",           "Snacks",  "Pantry",  30, 60, 90,  "Opened"),
    ("Peanut Brittle",       "Snacks",  "Pantry",  14, 30, 60,  "Homemade; commercial lasts longer"),
    ("Chana Chaat",          "Snacks",  "Fridge",  1,  2,  3,   "Prepared chickpea snack; popular in Pakistan"),
    ("Nimko",                "Snacks",  "Pantry",  30, 60, 90,  "Pakistani savory snack mix; opened bag"),
    ("Papad",                "Snacks",  "Pantry",  90, 180,365, "Uncooked dried lentil wafer; very shelf-stable"),
    ("Mathri",               "Snacks",  "Pantry",  14, 21, 30,  "Fried savory cracker; popular in Pakistan/India"),

    # ── CONDIMENTS & SAUCES ────────────────────────────────────────────────
    ("Hummus",               "Condiments & Sauces", "Fridge", 4, 5, 7, "Opened tub; store-bought. Homemade 3-4 days"),
    ("Tartar Sauce",         "Condiments & Sauces", "Fridge", 30,60,90, None),
    ("Ranch Dressing",       "Condiments & Sauces", "Fridge", 30,60,90, "Opened bottle"),
    ("Worcestershire Sauce", "Condiments & Sauces", "Pantry", 365, 730, 1095, "Unopened; once opened refrigerate, lasts 1-3 years"),
    ("Salsa",                "Condiments & Sauces", "Fridge", 5, 7, 10, "Opened jar"),
    ("Harissa Paste",        "Condiments & Sauces", "Fridge", 30,60,90, "Spicy North African paste"),
    ("Gochujang",            "Condiments & Sauces", "Fridge", 60,90,180, "Korean chili paste"),
    ("Mint Chutney",        "Condiments & Sauces","Fridge",3,  5,  7,  "Fresh prepared; no preservatives"),
    ("Tamarind Chutney",    "Condiments & Sauces","Fridge",14, 21, 30, "Imli ki chutney; cooked"),
    ("Coriander Chutney",   "Condiments & Sauces","Fridge",3,  5,  7,  "Fresh prepared"),
    ("Mango Chutney",       "Condiments & Sauces","Fridge",30, 60, 90, "Cooked/commercial; opened jar"),
    ("Green Chutney",       "Condiments & Sauces","Fridge",3,  5,  7,  "Fresh herbs; very perishable"),
    ("Raita",               "Condiments & Sauces","Fridge",1,  2,  3,  "Yogurt sauce; prepared"),
    ("Guacamole",           "Condiments & Sauces","Fridge",1,  2,  3,  "Homemade; oxidizes quickly"),
    ("Tzatziki",            "Condiments & Sauces","Fridge",3,  5,  7,  None),
    ("Aioli",               "Condiments & Sauces","Fridge",3,  5,  7,  "Homemade garlic mayo"),
    ("Pesto",               "Condiments & Sauces","Fridge",5,  7,  14, "Opened jar; homemade 3-5 days"),
    ("Chimichurri",         "Condiments & Sauces","Fridge",3,  5,  7,  "Fresh herb sauce"),
    ("Enchilada Sauce",     "Condiments & Sauces","Fridge",5,  7,  10, "Opened can"),
    ("Pasta Sauce (jar)",   "Condiments & Sauces","Fridge",5,  7,  10, "Opened jar"),
    ("Cream of Mushroom Soup","Condiments & Sauces","Fridge",3, 4,  5,  "Opened can"),
    ("Plum Sauce",          "Condiments & Sauces","Fridge",90, 180,365,"After opening"),
    ("Sweet Chilli Sauce",  "Condiments & Sauces","Fridge",90, 180,365,"After opening"),
    ("Garlic Paste",        "Condiments & Sauces","Fridge",7,  14, 21, "Commercial jar; homemade 3-5 days"),
    ("Ginger Paste",        "Condiments & Sauces","Fridge",7,  14, 21, "Commercial jar; adrak paste"),
    ("Ginger Garlic Paste", "Condiments & Sauces","Fridge",7,  14, 21, "Adrak lehsan paste; staple in Pakistani cooking"),

    # ── PREPARED MEALS ─────────────────────────────────────────────────────
    ("Sandwich",             "Prepared Meals","Fridge", 1, 2, 3, "Fresh-made"),
    ("Pizza Slice",          "Prepared Meals","Fridge", 2, 3, 4, "Cooked"),
    ("Sushi",                "Prepared Meals","Fridge", 1, 1, 2, "Best eaten same day"),
    ("Shawarma Wrap",        "Prepared Meals","Fridge", 1, 2, 3, "Cooked meat wrap"),
    ("Spring Rolls",         "Prepared Meals","Fridge", 2, 3, 4, "Cooked"),
    ("Pasta Salad",          "Prepared Meals","Fridge", 3, 4, 5, "With dressing"),
    ("Chicken Curry",        "Prepared Meals", "Fridge", 3, 3, 4, "Cooked dish; USDA recommends 3-4 days"),
    ("Daal (cooked)",       "Prepared Meals","Fridge", 3, 4, 5, "Any lentil preparation; USDA 3-4 days"),
    ("Biryani",             "Prepared Meals","Fridge", 2, 3, 4, "Cooked rice dish with meat"),
    ("Pulao",               "Prepared Meals","Fridge", 2, 3, 4, "Cooked rice dish"),
    ("Haleem",              "Prepared Meals","Fridge", 3, 4, 5, "Slow-cooked meat and lentil dish; popular in Pakistan"),
    ("Nihari",              "Prepared Meals","Fridge", 3, 4, 5, "Slow-braised beef stew; traditional Pakistani dish"),
    ("Keema",               "Prepared Meals","Fridge", 2, 3, 4, "Cooked minced meat"),
    ("Aloo Gosht",          "Prepared Meals","Fridge", 2, 3, 4, "Meat and potato curry"),
    ("Chana Masala",        "Prepared Meals","Fridge", 3, 4, 5, "Cooked chickpea curry"),
    ("Palak Paneer",        "Prepared Meals","Fridge", 2, 3, 4, "Spinach and paneer curry"),
    ("Baingan Bharta",      "Prepared Meals","Fridge", 2, 3, 4, "Roasted eggplant dish"),
    ("Cooked Rice",         "Prepared Meals","Fridge", 3, 4, 5, "Plain cooked; USDA 3-4 days; cool quickly"),
    ("Cooked Pasta",        "Prepared Meals","Fridge", 3, 4, 5, "Plain or with sauce"),
    ("Soup (Homemade)",     "Prepared Meals","Fridge", 3, 4, 5, "Any variety"),
    ("Fried Chicken",       "Prepared Meals","Fridge", 2, 3, 4, "Cooked"),
    ("Burger Patty (cooked)","Prepared Meals","Fridge",2, 3, 4, "Cooked beef/chicken patty"),
    ("Mac and Cheese",      "Prepared Meals","Fridge", 3, 4, 5, "Cooked; homemade or box"),
    ("Stir Fry",            "Prepared Meals","Fridge", 2, 3, 4, "Cooked vegetables and/or meat"),
    ("Fried Rice",          "Prepared Meals","Fridge", 2, 3, 4, "Cooked; reheat thoroughly"),
    ("Samosa (cooked)",     "Prepared Meals","Fridge", 2, 3, 4, "Fried pastry snack; popular in Pakistan"),
    ("Samosa (uncooked)",   "Prepared Meals","Freezer",30,60, 90,"Unbaked/unfried; freeze well"),
    ("Pakora",              "Prepared Meals","Fridge", 1, 2, 3, "Fried fritter; best eaten fresh"),
    ("Kebab (cooked)",      "Prepared Meals","Fridge", 2, 3, 4, "Any variety; cooked"),
    ("Dumplings (cooked)",  "Prepared Meals","Fridge", 2, 3, 4, None),
    ("Quiche",              "Prepared Meals","Fridge", 3, 4, 5, "Cooked"),
    ("Lasagna",             "Prepared Meals","Fridge", 3, 4, 5, "Cooked"),
    ("Tacos (assembled)",   "Prepared Meals","Fridge", 1, 2, 3, "Best eaten immediately"),
    ("Hummus (homemade)",   "Prepared Meals","Fridge", 3, 4, 5, "No preservatives; shorter than commercial"),

    # ── BREAKFAST FOODS ────────────────────────────────────────────────────
    ("Cornflakes",              "Breakfast Foods", "Pantry", 180,270,365,"Dry cereal"),
    ("Muesli",                  "Breakfast Foods", "Pantry", 180,270,365,"Sealed bag"),
    ("Pancake Mix",             "Breakfast Foods", "Pantry", 180,270,365,"Dry powder"),
    ("Waffles",                 "Breakfast Foods", "Fridge", 1, 2, 3, "Fresh-made"),
    ("Bagel with Cream Cheese", "Breakfast Foods", "Fridge", 2, 3, 4, None),
    ("Breakfast Burrito",       "Breakfast Foods", "Fridge", 2, 3, 4, "Cooked"),
    ("Scrambled Eggs",          "Breakfast Foods", "Fridge", 1, 2, 3, "Cooked"),
    ("Granola",                 "Breakfast Foods","Pantry",90, 180,365,"Opened bag; homemade shorter"),
    ("Porridge (cooked)",       "Breakfast Foods","Fridge",3,  4,  5,  "Cooked oatmeal; reheat with splash of water"),
    ("French Toast",            "Breakfast Foods","Fridge",2,  3,  4,  "Cooked"),
    ("Chia Pudding",            "Breakfast Foods","Fridge",3,  5,  7,  "Prepared; sealed container"),
    ("Overnight Oats",          "Breakfast Foods","Fridge",3,  5,  5,  "Prepared; sealed jar"),
    ("Halwa Poori",             "Breakfast Foods","Fridge",1,  2,  3,  "Cooked; popular Pakistani Sunday breakfast"),
    ("Halwa (Sooji)",           "Breakfast Foods","Fridge",2,  3,  4,  "Semolina halwa; cooked"),

    # ── CONFECTIONERY ─────────────────────────────────────────────────────
    ("Chocolate Bar",        "Confectionery","Pantry", 180,270,365,"Keep cool"),
    ("Hard Candy",           "Confectionery","Pantry", 365,730,1095,"Indefinite if dry"),
    ("Marshmallows",         "Confectionery","Pantry", 90, 120,180,"Opened bag"),
    ("Fudge",                "Confectionery","Pantry", 14, 21, 30, None),
    ("Truffles",             "Confectionery","Fridge", 7, 10, 14, "Handmade chocolates"),
    ("Gummy Bears",          "Confectionery","Pantry", 180,270,365,"Keep airtight"),
    ("Halva",                "Confectionery","Pantry", 90, 120,180,"Sesame sweet"),
    ("Milk Chocolate",      "Confectionery","Pantry",180,270,365,"Keep below 21°C"),
    ("Dark Chocolate",      "Confectionery","Pantry",365,540,730,"Higher cocoa content = longer life"),
    ("White Chocolate",     "Confectionery","Pantry",90, 180,270,"Shorter life than dark"),
    ("Toffee",              "Confectionery","Pantry",90, 180,365,"Wrapped; keep dry"),
    ("Caramel",             "Confectionery","Pantry",14, 30, 60, "Soft caramel; homemade"),
    ("Nougat",              "Confectionery","Pantry",30, 60, 90, "Wrapped"),
    ("Barfi",               "Confectionery","Fridge",3,  5,  7,  "Milk-based Pakistani/Indian sweet"),
    ("Gulab Jamun",         "Confectionery","Fridge",5,  7,  10, "In syrup; popular Pakistani/Indian mithai"),
    ("Kheer",               "Confectionery","Fridge",2,  3,  4,  "Rice pudding; popular in Pakistan"),
    ("Zarda",               "Confectionery","Fridge",2,  3,  4,  "Sweet saffron rice; Pakistani dessert"),
    ("Sewain",              "Confectionery","Fridge",2,  3,  4,  "Vermicelli pudding; Eid special in Pakistan"),
    ("Ladoo",               "Confectionery","Pantry",5,  7,  14, "Besan or motichoor; traditional mithai"),
    ("Jalebi",              "Confectionery","Pantry",1,  2,  3,  "Fresh fried; best same day"),
    ("Rasgulla",            "Confectionery","Fridge",5,  7,  10, "In syrup"),
    ("Lollipops",           "Confectionery","Pantry",365,730,1095,"Hard candy on stick; very long life"),
    ("Chewing Gum",         "Confectionery","Pantry",365,730,1095,"Stays safe indefinitely; flavor fades"),
    ("Cotton Candy",        "Confectionery","Pantry",1,  3,  7,  "Absorbs moisture quickly"),

    # ── BABY FOOD ─────────────────────────────────────────────────────────
    ("Infant Formula",       "Baby Food","Pantry", 365,540,730,"Unopened; use within 1 month after opening"),
    ("Baby Cereal",          "Baby Food","Pantry", 180,270,365,"Dry, sealed"),
    ("Pureed Carrots",       "Baby Food","Fridge", 2, 3, 4, "Opened jar"),
    ("Pureed Apples",        "Baby Food","Fridge", 2, 3, 4, None),
    ("Baby Pouches",         "Baby Food","Pantry", 180,270,365,"Unopened"),
    ("Toddler Snacks",       "Baby Food","Pantry", 90, 120,180,"Opened bag"),
    ("Rice Rusks",           "Baby Food","Pantry", 90, 120,180,"Dry snack for infants"),
]


def seed_shelf_life(db_session):
    """
    Insert all shelf_life_reference rows.
    Safe to run multiple times — skips rows that already exist.
    Call from your Alembic migration or a one-time setup script.
    """
    
    from app.models import ShelfLifeReference

    db = SessionLocal()
    inserted = 0
    for row in SHELF_LIFE_DATA:
        canonical_name, category, storage_context, min_d, avg_d, max_d, notes = row
        exists = db_session.query(ShelfLifeReference).filter_by(
            canonical_name=canonical_name,
            storage_context=storage_context,
        ).first()
        if not exists:
            db_session.add(ShelfLifeReference(
                canonical_name=canonical_name,
                category=category,
                storage_context=storage_context,
                shelf_life_days_min=min_d,
                shelf_life_days_avg=avg_d,
                shelf_life_days_max=max_d,
                notes=notes,
            ))
            inserted += 1

    db_session.commit()
    print(f"Seeded {inserted} shelf_life_reference rows ({len(SHELF_LIFE_DATA) - inserted} already existed)")
    db.close()

if __name__ == "__main__":
    db = SessionLocal()
    seed_shelf_life(db)
    db.close()