# ml_service/normalization/abbreviation_map.py

# The full map. 
# # Keys are uppercase preprocessed tokens; 
# values are canonical names that match exactly to rows in shelf_life_reference

ABBREVIATION_MAP = {

    # ── PRODUCE — Berries ────────────────────────────────────────────────────────
    "STRWBRY":        "Strawberries",
    "STRBRY":         "Strawberries",
    "STRWBRRY":       "Strawberries",
    "BLUBRY":         "Blueberries",
    "BLUBERY":        "Blueberries",
    "BLUEBERRY":      "Blueberries",
    "RSPBRY":         "Raspberries",
    "RASPBRY":        "Raspberries",
    "BLKBRY":         "Blackberries",
    "GRP":            "Grapes",
    "GRPES":          "Grapes",
    "RED GRAPES":     "Grapes",
    "GRN GRAPES":     "Grapes",
    "SEEDLESS GRP":   "Grapes",

    # ── PRODUCE — Stone & Tropical Fruits ────────────────────────────────────────
    "BNN":            "Bananas",
    "BNNA":           "Bananas",
    "BNNANA":         "Bananas",
    "PLT BANANAS":    "Bananas",
    "APPL":           "Apples",
    "APPLE":          "Apples",
    "GRN APPL":       "Apples",
    "FUJI APPL":      "Apples",
    "GALA APPL":      "Apples",
    "GRNSM APPL":     "Apples",
    "ORGN":           "Oranges",
    "ORNG":           "Oranges",
    "NAVEL ORNG":     "Oranges",
    "LMN":            "Lemons",
    "LEMN":           "Lemons",
    "LM":             "Limes",
    "LME":            "Limes",
    "PRSCN":          "Peaches",
    "PLUM":           "Plums",
    "PLM":            "Plums",
    "CHRRY":          "Cherries",
    "CHRY":           "Cherries",
    "MANGO":          "Mangoes",
    "MNGO":           "Mangoes",
    "SINDHRI":        "Mangoes",    # Pakistani variety
    "CHAUNSA":        "Mangoes",    # Pakistani variety
    "ANWAR RATOL":    "Mangoes",    # Pakistani variety
    "PPYA":           "Papayas",
    "PAPAYA":         "Papayas",
    "GUAVA":          "Guavas",
    "AMROOD":         "Guavas",     # Urdu
    "PGRNTE":         "Pomegranates",
    "POMGNT":         "Pomegranates",
    "ANAR":           "Pomegranates", # Urdu
    "WTRMLM":         "Watermelon",
    "WTRMLN":         "Watermelon",
    "TARBOOZ":        "Watermelon",  # Urdu
    "CNTLP":          "Cantaloupe",
    "CNTAL":          "Cantaloupe",
    "PNAPPL":         "Pineapple",
    "PNAPPLE":        "Pineapple",
    "PNEAPPL":        "Pineapple",
    "KIWI":           "Kiwi",
    "PEAR":           "Pears",
    "PRUNE":          "Prunes",
    "PSNFRUIT":       "Passionfruit",
    "PSN FRUIT":      "Passionfruit",
    "DRGNFRUIT":      "Dragonfruit",
    "DRGN FRUIT":     "Dragonfruit",
    "STRFRUIT":       "Starfruit",
    "STR FRUIT":      "Starfruit",
    "PRSMN":          "Persimmons",
    "PRSMMN":         "Persimmons",
    "CHRY":           "Cherries",
    "APRCT":          "Apricots",
    "APRICOT":        "Apricots",

    # ── PRODUCE — Vegetables ─────────────────────────────────────────────────────
    "TOM":            "Tomatoes",
    "TOMTO":          "Tomatoes",
    "TOMATOE":        "Tomatoes",
    "CHRY TOM":       "Cherry Tomatoes",
    "ROM TOM":        "Tomatoes",
    "GRAPE TOM":      "Cherry Tomatoes",
    "ONI":            "Onions",
    "ONIN":           "Onions",
    "ONION":          "Onions",
    "YLW ONI":        "Onions",
    "RED ONI":        "Onions",
    "PYAZ":           "Onions",     # Urdu
    "GRLC":           "Garlic",
    "GRIC":           "Garlic",
    "LAHSUN":         "Garlic",     # Urdu
    "POT":            "Potatoes",
    "PTAT":           "Potatoes",
    "PTATO":          "Potatoes",
    "ALOO":           "Potatoes",   # Urdu/Hindi
    "SWT POT":        "Sweet Potatoes",
    "SWPOT":          "Sweet Potatoes",
    "SHAKARKANDI":    "Sweet Potatoes", # Urdu
    "CARR":           "Carrots",
    "CARROT":         "Carrots",
    "GAJAR":          "Carrots",    # Urdu
    "BRCL":           "Broccoli",
    "BROC":           "Broccoli",
    "BROCCO":         "Broccoli",
    "CFLWR":          "Cauliflower",
    "CAULIFLWR":      "Cauliflower",
    "GOBI":           "Cauliflower", # Urdu/Hindi
    "CBGE":           "Cabbage",
    "CAB":            "Cabbage",
    "BNDGOBI":        "Cabbage",    # Urdu — literally "closed/bound cauliflower"
    "SPNCH":          "Spinach",
    "SPINCH":         "Spinach",
    "PALAK":          "Spinach",    # Urdu
    "LTT":            "Lettuce",
    "LETTC":          "Lettuce",
    "ICE LTT":        "Lettuce",
    "RMNE LTT":       "Lettuce",
    "CKE":            "Cucumber",
    "CUCMBR":         "Cucumber",
    "CUCUMB":         "Cucumber",
    "KHEERA":         "Cucumber",   # Urdu
    "BELL PEP":       "Bell Peppers",
    "BL PEP":         "Bell Peppers",
    "BLLPEP":         "Bell Peppers",
    "GRPEP":          "Bell Peppers",
    "RDPEP":          "Bell Peppers",
    "YLPEP":          "Bell Peppers",
    "SHIMLA MIRCH":   "Bell Peppers", # Urdu
    "JALPN":          "Jalapeños",
    "JLPNO":          "Jalapeños",
    "GRN CHILI":      "Green Chillies",
    "HARI MIRCH":     "Green Chillies", # Urdu
    "CORI":           "Coriander",
    "CORIAN":         "Coriander",
    "CORIANDER":      "Coriander",
    "CORIANDER LEAVES": "Coriander",
    "CORIANDER LEAF"  : "Coriander",
    "CILNTR":         "Coriander",
    "DHANIA":         "Coriander",  # Urdu
    "ANDAY":          "Eggs",       # Urdu/Pakistani retail token
    "ANDA":           "Eggs",
    "MACCHI":         "Fish",       # Urdu/Pakistani retail token
    "SAFAID MIRCH":   "White Pepper", # Urdu/Pakistani retail token
    "MNT":            "Mint",
    "MINT":           "Mint",
    "PODINA":         "Mint",       # Urdu
    "GRNONION":       "Green Onions",
    "SC ONI":         "Green Onions",
    "SCALL":          "Green Onions",
    "CELRY":          "Celery",
    "MSHM":           "Mushrooms",
    "MSHRM":          "Mushrooms",
    "PORT MSHRM":     "Mushrooms",
    "ZCHNI":          "Zucchini",
    "ZUCCH":          "Zucchini",
    "TORI":           "Zucchini",   # Urdu — ridge gourd/zucchini
    "EGPLT":          "Eggplant",
    "EGGPLNT":        "Eggplant",
    "BAINGAN":        "Eggplant",   # Urdu
    "CORN":           "Corn",
    "SWT CORN":       "Corn",
    "PEA":            "Peas",
    "PEAS":           "Peas",
    "MATAR":          "Peas",       # Urdu
    "GRBN":           "Green Beans",
    "GRN BNS":        "Green Beans",
    "GRBN BNS":       "Green Beans",
    "OKRA":           "Okra",
    "BHINDI":         "Okra",       # Urdu
    "BITTER GOURD":   "Bitter Gourd",
    "KARELA":         "Bitter Gourd", # Urdu
    "BOTTLE GOURD":   "Bottle Gourd",
    "LAUKI":          "Bottle Gourd", # Urdu
    "DRUMSTICK":      "Drumstick",
    "SAIJAN":         "Drumstick",  # Urdu — moringa pods
    "METHI":          "Fenugreek Leaves", # Urdu
    "TURNIP":         "Turnips",
    "SHALGAM":        "Turnips",    # Urdu
    "RADISH":         "Radishes",
    "MOOLI":          "Radishes",   # Urdu
    "BEETROOT":       "Beetroot",
    "CHNTNGE":        "Chestnut",
    "ARTICHOKE":      "Artichoke",
    "ASPRGUS":        "Asparagus",
    "ASPAR":          "Asparagus",
    "KALE":           "Kale",
    "CHARD":          "Swiss Chard",
    "ARUGULA":        "Arugula",
    "KALE":           "Kale",
    "ASPRGS":         "Asparagus",
    "ASPRGUS":        "Asparagus",
    "OKRA":           "Okra",
    "BHNDI":          "Okra",   # Hindi/Urdu

    # ── DAIRY ────────────────────────────────────────────────────────────────────
    "MLKWHL":         "Whole Milk",
    "MLK WHL":        "Whole Milk",
    "WHL MLK":        "Whole Milk",
    "MILK":           "Whole Milk",
    "MLK":            "Whole Milk",
    "SKM MLK":        "Skim Milk",
    "SKMMLK":         "Skim Milk",
    "2% MLK":         "Whole Milk",
    "FL CRM MLK":     "Full Cream Milk",
    "FULL CRM":       "Full Cream Milk",
    "FULLCRM MLK":    "Full Cream Milk",
    "UHT MLK":        "UHT Milk",
    "TETRA MLK":      "UHT Milk",
    "NESTLE MLK":     "UHT Milk",   # Nestle Milkpak — dominant Pakistani brand
    "MILKPAK":        "UHT Milk",
    "HLF HLF":        "Half and Half",
    "HVY CRM":        "Heavy Cream",
    "WHPNG CRM":      "Whipped Cream",
    "BTR":            "Butter",
    "BUTR":           "Butter",
    "UNSLT BTR":      "Butter",
    "SLTED BTR":      "Butter",
    "CHDR":           "Cheddar Cheese",
    "CHEDDR":         "Cheddar Cheese",
    "SHRP CHDR":      "Cheddar Cheese",
    "MOZZ":           "Mozzarella Cheese",
    "MOZZAR":         "Mozzarella Cheese",
    "CRM CHSE":       "Cream Cheese",
    "CRMCHS":         "Cream Cheese",
    "PHILLY":         "Cream Cheese", # Philadelphia cream cheese
    "CTG CHSE":       "Cottage Cheese",
    "CTGCHSE":        "Cottage Cheese",
    "GRK YGRT":       "Greek Yogurt",
    "GRKYGRT":        "Greek Yogurt",
    "GRK YGT":        "Greek Yogurt",
    "YGRT":           "Plain Yogurt",
    "YOGURT":         "Plain Yogurt",
    "PLN YGRT":       "Plain Yogurt",
    "DAHI":           "Dahi",
    "LASSI":          "Lassi",
    "MANGO LASSI":    "Lassi",
    "PANER":          "Paneer",
    "PANIR":          "Paneer",
    "PANEER":         "Paneer",
    "EGG":            "Eggs",
    "EGGS":           "Eggs",
    "LRG EGG":        "Eggs",
    "XL EGGS":        "Eggs",
    "BRWN EGG":       "Eggs",
    "SRC CRM":        "Sour Cream",
    "SRCRM":          "Sour Cream",
    "COND MLK":       "Condensed Milk",
    "CONDMLK":        "Condensed Milk",
    "BRIE":           "Brie Cheese",
    "BRI":            "Brie Cheese",
    "FETA":           "Feta Cheese",
    "RICOTTA":        "Ricotta Cheese",
    "EVAP MLK":       "Evaporated Milk",
    "EVAPORATED":     "Evaporated Milk",
    "KEFIR":          "Kefir",
    "BUTTERMILK":     "Buttermilk",
    "CAMEMBERT":      "Camembert",

    # ── MEAT ─────────────────────────────────────────────────────────────────────
    "CHKN BRST":      "Chicken Breast",
    "CHKNBRST":       "Chicken Breast",
    "CHKN BRS":       "Chicken Breast",
    "CHICK BRST":     "Chicken Breast",
    "CHKN THGH":      "Chicken Thighs",
    "CHKNTHGH":       "Chicken Thighs",
    "CHKN DRST":      "Chicken Thighs",
    "WHL CHKN":       "Whole Chicken",
    "WHLCHKN":        "Whole Chicken",
    "MURG":           "Chicken Breast", # Urdu for chicken (general)
    "MURGH":          "Chicken Breast",
    "MURG BRST":      "Chicken Breast",
    "MURG QEEMA":     "Minced Chicken",
    "CHKN QEEMA":     "Minced Chicken",
    "QEEMA MURG":     "Minced Chicken",
    "GRND BEEF":      "Ground Beef",
    "GRNDBEEF":       "Ground Beef",
    "BF GRND":        "Ground Beef",
    "BEEF QEEMA":     "Minced Beef",
    "GOSHT QEEMA":    "Minced Beef",  # Urdu — gosht = meat/beef/mutton
    "QEEMA":          "Minced Beef",
    "KEEMA":          "Minced Beef",
    "BF STK":         "Beef Steak",
    "BFSTK":          "Beef Steak",
    "SIRLOIN":        "Beef Steak",
    "RIBEYE":         "Beef Steak",
    "MUTN":           "Mutton",
    "MUTTON":         "Mutton",
    "GOSHT":          "Mutton",       # Urdu (often mutton specifically)
    "LMB CHPS":       "Lamb Chops",
    "LMBCHPS":        "Lamb Chops",
    "CHOPS":          "Lamb Chops",
    "PRK CHP":        "Pork Chops",
    "PRKCHS":         "Pork Chops",
    "BCN":            "Bacon",
    "BACON":          "Bacon",
    "SLMN":           "Salmon",
    "SLMON":          "Salmon",
    "ATLNT SLMN":     "Salmon",
    "TNA STK":        "Tuna Steak",
    "TUNA":           "Tuna Steak",
    "SHRMP":          "Shrimp",
    "SHRIMP":         "Shrimp",
    "JHINGA":         "Shrimp",       # Urdu
    "SCLLPS":         "Scallops",
    "DLI HM":         "Deli Ham",
    "DELIHAM":        "Deli Ham",
    "DLI TRK":        "Deli Turkey",
    "SSGE":           "Sausages",
    "SAUSAGE":        "Sausages",
    "LNKSSGE":        "Sausages",
    "HTDOG":          "Hot Dogs",
    "HOT DOG":        "Hot Dogs",
    "SEEKH KB":       "Seekh Kebab",
    "SEEKH KBAB":     "Seekh Kebab",
    "SK KEBAB":       "Seekh Kebab",
    "BIHARI KB":      "Seekh Kebab",  # Similar kebab variety
    "TIKKA":          "TIKKA",
    "TKA":            "TIKKA",  
    "TRKY BRST":      "Turkey Breast",
    "DUCK LEG":       "Duck Legs",
    "VENISON":        "Venison",
    "GOAT":           "Goat Meat",
    "CRAB":           "Crab",
    "LOBSTR":         "Lobster",
    "CLM":            "Clams",
    "OYSTER":         "Oysters",

    # ── BAKERY ───────────────────────────────────────────────────────────────────
    "BRD":            "Bread",
    "BREAD":          "Bread",
    "WW BRD":         "Whole Wheat Bread",
    "WWBRD":          "Whole Wheat Bread",
    "SLCD BRD":       "Bread",
    "PITA":           "Pita Bread",
    "PTABRD":         "Pita Bread",
    "NAAN":           "Naan",
    "NAN":            "Naan",
    "GARLIC NAAN":    "Naan",
    "ROTI":           "Roti",
    "CHAPATI":        "Roti",
    "CHAPATTI":       "Roti",
    "PRATHA":         "Paratha",
    "PARATHA":        "Paratha",
    "PRATHA PLN":     "Paratha",
    "ALOO PRTHA":     "Paratha",
    "CRSNT":          "Croissants",
    "CROISSANT":      "Croissants",
    "BAGEL":          "Bagels",
    "MUFFIN":         "Muffins",
    "BLBN MFFN":      "Muffins",
    "SCONE":          "Scones",
    "BROWNIE":        "Brownies",
    "CUPCAKE":        "Cupcakes",
    "TART":           "Tarts",
    "ECLAIR":         "Eclairs",
    "DONUT":          "Donuts",

    # ── PANTRY — Grains & Staples ────────────────────────────────────────────────
    "PST":            "Pasta",
    "PASTA":          "Pasta",
    "SPAGHTTI":       "Pasta",
    "PENNE":          "Pasta",
    "FETTUC":         "Pasta",
    "MACRNI":         "Pasta",
    "RICE":           "Rice",
    "WH RICE":        "Rice",
    "BSMTI":          "Basmati Rice",
    "BASMATI":        "Basmati Rice",
    "JASMINE RICE":   "Rice",
    "BRN RICE":       "Rice",
    "CHAWAL":         "Rice",         # Urdu
    "OATS":           "Oats",
    "ROLLD OATS":     "Oats",
    "QUCK OATS":      "Oats",
    "FLR":            "Flour",
    "FLOUR":          "Flour",
    "AP FLR":         "Flour",
    "ATTA":           "Atta Flour",
    "ATT FLR":        "Atta Flour",
    "MAIDA":          "Maida",
    "SUJI":           "Semolina",     # Urdu — semolina/cream of wheat
    "SEMOLINA":       "Semolina",
    "SGR":            "Sugar",
    "SUGAR":          "Sugar",
    "BRWN SGR":       "Sugar",
    "PWDR SGR":       "Sugar",
    "SLT":            "Salt",
    "SALT":           "Salt",
    "OLV OIL":        "Olive Oil",
    "OLVOL":          "Olive Oil",
    "EVOO":           "Olive Oil",
    "VEG OIL":        "Vegetable Oil",
    "VEGOL":          "Vegetable Oil",
    "SUNFLR OIL":     "Vegetable Oil",
    "CANOLA":         "Vegetable Oil",
    "COOKING OIL":    "Cooking Oil",
    "DALA OIL":       "Cooking Oil",  # Generic local brand type
    "SUFI OIL":       "Cooking Oil",  # Pakistani brand
    "DALDA":          "Cooking Oil",  # Major Pakistani cooking oil/ghee brand
    "GHEE":           "Ghee",
    "DESI GHEE":      "Ghee",
    "VANSP GHEE":     "Ghee",         # Vanaspati — hydrogenated vegetable ghee
    "COUSC":          "Couscous",
    "MILLET":         "Millet",
    "BARLEY":         "Barley",
    "RYE FLR":        "Rye Flour",
    "BROWN SGR":      "Brown Sugar",
    "MAPLE SYRUP":    "Maple Syrup",
    "TAHINI":         "Tahini",
    "MOLASSES":       "Molasses",
    "COCONUT OIL":    "Coconut Oil",

    # ── PANTRY — Condiments & Sauces ─────────────────────────────────────────────
    "SOY SCS":        "Soy Sauce",
    "SOYSCS":         "Soy Sauce",
    "KTCHP":          "Ketchup",
    "KETCHUP":        "Ketchup",
    "MAYO":           "Mayonnaise",
    "MAYONNSE":       "Mayonnaise",
    "MSTRD":          "Mustard",
    "MUSTARD":        "Mustard",
    "HT SCS":         "Hot Sauce",
    "HTSCS":          "Hot Sauce",
    "SRIRACHA":       "Hot Sauce",
    "TABASCO":        "Hot Sauce",
    "VINEGR":         "Vinegar",
    "VINEGAR":        "Vinegar",
    "AP VNG":         "Vinegar",
    "WH VNG":         "Vinegar",
    "PNUT BTR":       "Peanut Butter",
    "PNUTBTR":        "Peanut Butter",
    "PB":             "Peanut Butter",
    "STRWBRY JAM":    "Jam",
    "JAM":            "Jam",
    "MARMALADE":      "Jam",
    "TOM SCS":        "Tomato Sauce",
    "TOMSCS":         "Tomato Sauce",
    "MARINARA":       "Tomato Sauce",
    "TOM PST":        "Tomato Paste",
    "TOMPST":         "Tomato Paste",
    "CCNT MLK":       "Coconut Milk",
    "CCNTM":          "Coconut Milk",
    "CHKN BRTH":      "Chicken Broth",
    "CHKNBRTH":       "Chicken Broth",
    "VEG BRTH":       "Chicken Broth",

    # ── PANTRY — Legumes ─────────────────────────────────────────────────────────
    "LNTLS":          "Lentils",
    "LENTIL":         "Lentils",
    "RED LNTL":       "Masoor Dal",
    "MASOOR":         "Masoor Dal",
    "MSOOR DAL":      "Masoor Dal",
    "CHKPEAS":        "Chickpeas",
    "CHNPEAS":        "Chickpeas",
    "CHANA":          "Chickpeas",
    "KABLI CHANA":    "Chickpeas",
    "BLK BNS":        "Black Beans",
    "RDNY BNS":       "Kidney Beans",
    "KDY BNS":        "Kidney Beans",
    "RAJMA":          "Kidney Beans",  # Urdu
    "CHANA DAL":      "Chana Dal",
    "MOONG DAL":      "Moong Dal",
    "MUNG DAL":       "Moong Dal",
    "URAD DAL":       "Urad Dal",
    "MASH DAL":       "Urad Dal",      # Pakistani name for urad dal
    "TOOR DAL":       "Toor Dal",
    "ARHAR DAL":      "Toor Dal",      # Alternative name

    # ── PANTRY — Canned Goods ────────────────────────────────────────────────────
    "CND CHKP":       "Canned Chickpeas",
    "CND TOMATO":     "Canned Tomatoes",
    "CNDTOM":         "Canned Tomatoes",
    "DICED TOM":      "Canned Tomatoes",
    "CND TUNA":       "Canned Tuna",
    "TNA CAN":        "Canned Tuna",

    # ── BEVERAGES ────────────────────────────────────────────────────────────────
    "OJ":             "Orange Juice",
    "ORNG JCE":       "Orange Juice",
    "ORANGE JCE":     "Orange Juice",
    "APPL JCE":       "Apple Juice",
    "SPRKLNG WTR":    "Sparkling Water",
    "SPKL WTR":       "Sparkling Water",
    "SODA":           "Soda",
    "CLA":            "Soda",          # Cola
    "COLA":           "Soda",
    "PEPSI":          "Soda",
    "COKE":           "Soda",
    "7UP":            "Soda",
    "SPRITE":         "Soda",
    "CFE BNSE":       "Coffee Beans",
    "COFFEE":         "Coffee Beans",
    "GRND CFE":       "Ground Coffee",
    "INST CFE":       "Ground Coffee",
    "TEA":            "Tea Bags",
    "TEABAG":         "Tea Bags",
    "GRN TEA":        "Tea Bags",
    "BLK TEA":        "Tea Bags",
    "CHAI":           "Tea Bags",
    "LIPTON":         "Tea Bags",      # Dominant brand in Pakistan/globally
    "TAPAL":          "Tea Bags",      # Pakistani brand
    "BROOKE BOND":    "Tea Bags",      # Common in Pakistan/UK
    "PNAPL JCE":      "Pineapple Juice",
    "CRNBRY JCE":     "Cranberry Juice",
    "GRN TEA LEAF":   "Green Tea Leaves",
    "HRBL TEA":       "Herbal Tea",
    "INSTNT CFE":     "Instant Coffee",
    "ENERGY DRNK":    "Energy Drink",

    # ── FROZEN ───────────────────────────────────────────────────────────────────
    "FRZ PEAS":       "Frozen Peas",
    "FRZPEAS":        "Frozen Peas",
    "FRZ CORN":       "Frozen Corn",
    "FRZ SPNCH":      "Frozen Spinach",
    "FRZ MX VG":      "Frozen Mixed Veg",
    "FRZN MIX":       "Frozen Mixed Veg",
    "FRZ FRIES":      "Frozen Fries",
    "FRZNFRI":        "Frozen Fries",
    "ICE CRM":        "Ice Cream",
    "ICECREAM":       "Ice Cream",
    "FRZ PIZZA":      "Frozen Pizza",
    "FRZPIZZA":       "Frozen Pizza",
    "FRZ WFFL":       "Frozen Waffles",
    "FRZ STRWBRY":    "Frozen Strawberries",
    "FRZ MANGO":      "Frozen Mango",
    "FRZ BROC":       "Frozen Broccoli",
    "FRZ NUGGETS":    "Frozen Chicken Nuggets",
    "FRZ FISH":       "Frozen Fish Fillets",
    "FRZ DUMPLNG":    "Frozen Dumplings",

    # ── GRAINS — Spices (common receipt appearances) ──────────────────────────────
    "BLCK PPPR":      "Black Pepper",
    "BLK PPPR":       "Black Pepper",
    "KALI MIRCH":     "Black Pepper",  # Urdu
    "RED PPPR":       "Red Pepper",
    "LAAL MIRCH":     "Red Pepper",    # Urdu
    "CMIN":           "Cumin",
    "CUMIN":          "Cumin",
    "ZEERA":          "Cumin",         # Urdu
    "TURMRC":         "Turmeric",
    "TURMER":         "Turmeric",
    "HALDI":          "Turmeric",      # Urdu
    "CRDR":           "Coriander Powder",
    "CORIANDER PWD":  "Coriander Powder",
    "DHANIA PWD":     "Coriander Powder",
    "GRMSALA":        "Garam Masala",
    "GARAM MSLA":     "Garam Masala",
    "CHILI PWD":      "Chili Powder",
    "MIRCH PWD":      "Chili Powder",  # Urdu
    "CINNMN":         "Cinnamon",
    "DARCHINI":       "Cinnamon",      # Urdu
    "CINMN":          "Cinnamon",
    "CARDMM":         "Cardamom",
    "ILLAICHI":       "Cardamom",      # Urdu
    "CLVS":           "Cloves",
    "LAUNG":          "Cloves",        # Urdu
    "BAY LEAF":       "Bay Leaves",
    "TEJPTTA":        "Bay Leaves",    # Urdu
    
    # ── SNACKS ───────────────────────────────────────────────────────────
    "CHIPS":          "Potato Chips",
    "POT CHIPS":      "Potato Chips",
    "PRETZEL":        "Pretzels",
    "TRL MIX":        "Trail Mix",
    "POPCORN":        "Popcorn",
    "GRNLA BAR":      "Granola Bars",
    "RICE CRKR":      "Rice Crackers",
    "CHEESE PUFF":    "Cheese Puffs",
    "JERKY":          "Beef Jerky",
    "FRUIT LTHR":     "Fruit Leather",
    "SEAWEED":        "Seaweed Snacks",
    "CRACKER":        "Crackers",

    # ── CONDIMENTS & SAUCES ──────────────────────────────────────────────
    "HUMMUS":         "Hummus",
    "TARTAR":         "Tartar Sauce",
    "RANCH":          "Ranch Dressing",
    "WORCESTER":      "Worcestershire Sauce",
    "SALSA":          "Salsa",
    "HARISSA":        "Harissa Paste",
    "GOCHUJANG":      "Gochujang",
    "BBQ SCS":        "BBQ Sauce",
    "PESTO":          "Pesto",
    "FISH SCS":       "Fish Sauce",
    "CHILI SCS":      "Chili Sauce",

    # ── PREPARED MEALS ───────────────────────────────────────────────────
    "SANDWICH":       "Sandwich",
    "PIZZA SLICE":    "Pizza Slice",
    "SUSHI":          "Sushi",
    "SHAWARMA":       "Shawarma Wrap",
    "SPRNG ROLL":     "Spring Rolls",
    "PASTA SALAD":    "Pasta Salad",
    "CHKN CURRY":     "Chicken Curry",
    "LASAGNA":        "Lasagna",
    "BIRYANI":        "Biryani",

    # ── BREAKFAST FOODS ──────────────────────────────────────────────────
    "CORNFLKS":       "Cornflakes",
    "MUESLI":         "Muesli",
    "PNCK MIX":       "Pancake Mix",
    "WAFFLE":         "Waffles",
    "BGL CRMCHS":     "Bagel with Cream Cheese",
    "BRKFST BURRITO": "Breakfast Burrito",
    "SCRMBLD EGG":    "Scrambled Eggs",

    # ── CONFECTIONERY ───────────────────────────────────────────────────
    "CHOC BAR":       "Chocolate Bar",
    "HARD CNDY":      "Hard Candy",
    "MARSHMALLOW":    "Marshmallows",
    "FUDGE":          "Fudge",
    "TRUFFLE":        "Truffles",
    "GUMMY":          "Gummy Bears",
    "HALVA":          "Halva",

    # ── BABY FOOD ───────────────────────────────────────────────────────
    "INFNT FORMULA":  "Infant Formula",
    "BABY CEREAL":    "Baby Cereal",
    "PUREE CARROT":   "Pureed Carrots",
    "PUREE APPLE":    "Pureed Apples",
    "BABY POUCH":     "Baby Pouches",
    "TODDLER SNACK":  "Toddler Snacks",
    "RICE RUSK":      "Rice Rusks",
    
}


def pass1_lookup(cleaned_token: str) -> str | None:
    """
    Direct dictionary lookup. Returns canonical name or None on miss.
    Tries exact match first, then a joined-words variant.
    """
    result = ABBREVIATION_MAP.get(cleaned_token.upper())
    if result:
        return result

    # Try collapsing spaces: "CHKN BRST" might appear as "CHKNBRST"
    collapsed = cleaned_token.upper().replace(" ", "")
    return ABBREVIATION_MAP.get(collapsed)