"""create shelf_life_reference and normalization_cache

Revision ID: c04767df306c
Revises: 
Create Date: 2026-06-09 20:06:24.240005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04767df306c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalization_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_token', sa.String(length=200), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_token')
    )
    op.create_table('shelf_life_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('storage_context', sa.String(length=20), nullable=False),
    sa.Column('shelf_life_days_min', sa.Integer(), nullable=False),
    sa.Column('shelf_life_days_avg', sa.Integer(), nullable=False),
    sa.Column('shelf_life_days_max', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf_life_reference')
    op.drop_table('normalization_cache')
    # ### end Alembic commands ###
